### ISSUE TITLE
Update Almanak organizations and persons extractors

### ISSUE THREAD

**Issue by voodoo-burger** [openstate/open-raadsinformatie#100]
The Almanak has changed it's source HTML again causing its OrganisationsExtractor and PersonsExtractor to break.

**Comment by breyten** [comment]
Maybe also see [https://allmanak.nl/api](the Allmanak API) which imports the XML of the Almanak :)

**Comment by voodoo-burger** [comment]
> Maybe also see [https://allmanak.nl/api](the Allmanak API) which imports the XML of the Almanak :)

I've fixed it for now but it might be a good idea to switch to this in the future.
