### ISSUE TITLE
Upgrade Python and packages

### ISSUE THREAD

**Issue by jorritb** [openstate/open-raadsinformatie#105]
`DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.`

Aside from Python itself, there are also a lot of packages that have newer versions.

**Comment by jurrian** [comment]
Will be done somewhere in the longterm

**Comment by voodoo-burger** [comment]
As far as updating the actual code, [2to3](https://docs.python.org/2/library/2to3.html) is a useful tool.

**Comment by jurrian** [comment]
We will investigate upgrading to python 3.x, if nothing breaks we will deploy it soon.

**Comment by jurrian** [comment]
Upgrade has been completed by @jorritb
