### ISSUE TITLE
Mount source definition files as external volume

### ISSUE THREAD

**Issue by voodoo-burger** [openstate/open-raadsinformatie#106]
Currently the whole deployment needs to be rebuilt and/or restarted when source files have to be modified (ie to add a municipality). This could probably be made easier by mounting the sources folder as an external volume.

Suggestion by @jurrian

**Comment by jurrian** [comment]
I have thought about this a lot and in the end I decided to go for removing source definitions fast changing settings like start_date and saving those in Redis. Also all the sources are added in Redis and tagged with one or more configurations to add some flexibility. The new command for this is `python manage.py extract process <configuration name>`
