### ISSUE TITLE
@type field in v1 should either be a keyword field or set fielddata to true

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#108]
When I'm trying to filter by `@type` in [the new ori-search](https://github.com/ontola/ori-search/), I'm getting the following error:

`Fielddata is disabled on text fields by default. Set fielddata=true on [@type] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.`

@jurrian

**Comment by breyten** [comment]
The mapping should be updated -- probably due to moving to ES7

**Comment by jurrian** [comment]
Correct, we were not using `es_mappings/ori_template.json` so I reinstated it. Using dynamic_templates all string type fields are now mapped as a keyword, this in turn can be overruled by specifying the text fields explicitly.
