### ISSUE TITLE
Change documentation v1

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#109]

**Comment by joepio** [comment]
The REST API (#107) will become the main API, so it should be documented in a complete fashion. @fletcher91 is working on this.

**Comment by joepio** [comment]
Minimal API v1 docs: https://id.openraadsinformatie.nl/

**Comment by joepio** [comment]
WIP: https://github.com/ontola/ori-search/blob/master/docs.md

**Comment by jurrian** [comment]
As per #145  all not existing requests will be sent to the docs mentioned above.
