### ISSUE TITLE
Wrong AgendaItem name in Notubiz municipalities - uses Meeting name

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#117]
There's something funny going on here: https://id.openraadsinformatie.nl/44289 ([view in search](http://ori.argu.co/?searchbox=%22wat%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F44289))

![Selection_012](https://user-images.githubusercontent.com/2183313/58103409-347e5d00-7be3-11e9-9978-be21cc8ad62c.png)

All the Agenda Item names are the same. @jurrian is this weird usage or a problem with importing?

**Comment by jurrian** [comment]
The correct attribute for the name of the AgendaItem seems to be `http://schema.org/description` instead of `http://schema.org/name`

**Comment by joepio** [comment]
Let's wait until the data has been loaded, and I'll check whether the duplicate names are still there.

**Comment by joepio** [comment]
@jurrian The problem is still there. The correct name is serialized as a schema:description, and the wrong one (the Meeting name) as schema:name. I could change the views in ori-search, but the problem is with the mapping.

The schema:description should only be used for longer, optional descriptions, and not for the main name of the content. Currently, the schema:name shows the name of the meeting, which probably should not have been included at all.

Either the municipality (e.g. [groningen](https://ori.argu.co/search?zoekterm="raad+rekening"&datums=%5B"2019-03-01"%2C"2019-10-04"%5D&organisaties=%5B"ori_groningen_20190809125025"%5D&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F37960&type=%5B"AgendaItem"%5D)) uses the tool in a really weird way, or something else is going on.

**Comment by joepio** [comment]
https://github.com/openstate/open-raadsinformatie/blob/7f38ff63a48619444faf9199e8bcb5c53dbd42bd/ocd_backend/transformers/notubiz_meeting.py#L72

I think this needs to be set to name
