### ISSUE TITLE
Get list of classification (remove need for query)

### ISSUE THREAD

**Issue by tomkunzler** [openstate/open-raadsinformatie#12]
Utrecht wanted to get a list of 'moties' for example. Now you can only get results when you enter a query. 

Concrete request: A possibility of getting every motie or document type (classification) listed as search result when you click on the document type would be a nice to have feature, independent of a query or search entry. This will bypass the need to enter a specific query. 

Maybe when build in this feature would also be nice for the search.opencultuurdata.nl.

Hope I clarified this enough in this way :-).

**Comment by breyten** [comment]
Next time, for search please in the [openstate/ori-search](https://github.com/openstate/ori-search) repo :-)
