### ISSUE TITLE
Add property with link to original meeting / agenda item

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#121]
I'd like to be able to link to the HTML representation of a meeting / agenda item. This creates legitimacy and is useful during development.

**Comment by joepio** [comment]
Unfortunately, this data is missing from both the Notubiz and iBabs APIs. This means that the only way to solve this on our side, is to implement all the relevant paths and routing logic. This is too costly. I'll try to contact the source systems and ask if they could implement a link to their HTML representation.

**Comment by joepio** [comment]
I've sent mails to Notubiz and iBabs and requested that they include a link to the HTML representation in their API.

**Comment by joepio** [comment]
Notubiz will report back in two weeks.

**Comment by joepio** [comment]
Notubiz will add this feature. When this will happen is not clear yet.

**Comment by joepio** [comment]
From notubiz:

```
Beste Joep,

We boeken de aanpassing in 1 van de komende ontwikkelsprints in. Naar verwachting komt het dan met de release van 12 augustus beschikbaar op de productie-omgeving. Mocht dat niet lukken dan sowieso de release erna welke op 9 september is.  
```

**Comment by joepio** [comment]
New reply from notubiz:

> Verder kan ik je wel melden dat we de URL / link naar de vergaderingen af hebben en deze dus met de release van 12 augustus op productie beschikbaar komt. Even onder voorbehoud dat de acceptatietest van de release goed gaat de komende 2 weken maar daar verwacht ik geen problemen mee.

**Comment by joepio** [comment]
The Notubiz feature will be released next week.

**Comment by jurrian** [comment]
Is there documentation about this? Which version of Notubiz?
