### ISSUE TITLE
Resolve cached source files

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#123]
We try to cache all the sources that we process by saving the suppliers response to the GC Storage. This way we can always access the source even if the suppliers version is protected using a whitelist or does not have an explicit url like in SOAP. A reference to the cached source can be made in the metadata, see #112 .

- [ ] iBabs
- [X] Notubiz
- [ ] Gemeente Oplossingen
- [ ] Greenvalley
- [ ] Parleaus
- [X] GGM

**Comment by jurrian** [comment]
@jorritb can you take this one when you have time?

**Comment by joepio** [comment]
we no longer use gc
