### ISSUE TITLE
"None" as name

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#124]
This resource https://id.openraadsinformatie.nl/243815 has a schema:name of "None". I suspect this is due to a transformation problem, and not due to source data.

**Comment by voodoo-burger** [comment]
This seems to be a problem with the source data from certain municipalities - they don't always provide the title of the meeting in the `description` field. The ones affected that I've found so far are Goirle, Den Helder, Leiderdorp, Doetinchem, Oude IJsselstreek, Borne and Bloemendaal.

I don't really see a way to solve this, except for contacting them and asking them to use the description field.

I've changed "None" to "Geen titel" to make it a little more readable.

**Comment by joepio** [comment]
I think we should not store any title at all, if there is none. We should not create data that does not exist. 

If, for any reason, a title is absolutely necessary, I suggest creating something like this:

`Vergadering - Raad - 2019-04-24`
`Vergadering - ${commision_name} - ${start_date}

**Comment by voodoo-burger** [comment]
`name` is a required attribute for a meeting. I will implement @joepio's suggestion.

**Comment by akuckartz** [comment]
> name is a required attribute for a meeting.

Where is that specified?

**Comment by voodoo-burger** [comment]
> > name is a required attribute for a meeting.
> 
> Where is that specified?

This is specified in the model definition of `Meeting`: https://github.com/openstate/open-raadsinformatie/blob/4a42c726fd37f451c4515f5103277fa494b73441/ocd_backend/models/definitions/meeting.py#L30 .
