### ISSUE TITLE
Integrate OpenState Allmanak into ORI

### ISSUE THREAD

**Issue by jorritb** [openstate/open-raadsinformatie#134]
Openstate has indicated that their enhanced government almanak service ([allmanak.nl](https://allmanak.nl)) is ready for use. This allmanak can replace the web scraping of the current government almanak, which is frequently unreliable because the data is inaccurate or the scraper breaks due to changes in the source HTML.

**Comment by breyten** [comment]
I need more reaction emoji's ;) (aka keep up the good work!)

**Comment by voodoo-burger** [comment]
> I need more reaction emoji's ;) (aka keep up the good work!)

I should be the one thanking you guys for making this, because getting rid of all the web scraping nonsense will make things a lot more stable and accurate @bwbroersma ;)

**Comment by bwbroersma** [comment]
Just tell me what you need and I'll (help you) write a PostgREST query for https://www.allmanak.nl/api/

e.g. just fetching all almanak Raadsleden & Wethouders and municipality logos (which would be a one on one replacement):
[`https://rest-api.allmanak.nl/v0/overheidsorganisatie?type=eq.Gemeente&einddatum=is.null&afkorting=eq.Delft&select=naam,ictucode,logo(url,backgroundcolor,license),website:contact-%3Einternet,functies(functie:functieid(naam,medewerkers(persoon:persoonid(naam,partij))))&functies.functie.naam=in.(Raadslid,Wethouder)`](https://rest-api.allmanak.nl/v0/overheidsorganisatie?type=eq.Gemeente&einddatum=is.null&afkorting=eq.Delft&select=naam,ictucode,logo(url,backgroundcolor,license),website:contact-%3Einternet,functies(functie:functieid(naam,medewerkers(persoon:persoonid(naam,partij))))&functies.functie.naam=in.(Raadslid,Wethouder))

Remove `&afkorting=eq.Delft` to fetch all municipalities

We also have enrichment's and matches with the Kiesraad data thanks to our previous intern @bash- creating https://github.com/openstate/almanak-kiesraad-matcher

**Comment by voodoo-burger** [comment]
Steps:

1. Replace `ocd_backend.extractors.odata.ODataExtractor` for top-level municipality/province extraction
2. Replace `ocd_backend.extractors.almanak.OrganisationsExtractor` for party extraction
3. Replace `ocd_backend.extractors.almanak.PersonsExtractor` for person extraction
4. For iBabs: decide whether to use iBabsPerson or the new allmanak (@jurrian?)

Other things to do:

- Create a new ProvinceOrganisationItem
- Rename organisations to parties
- Add councils once #139 is decided

**Comment by voodoo-burger** [comment]
@bwbroersma I can use your example query to get a list of persons in a municipality or province, thanks for that. Can you also give me a query for a list of parties per municipality or province?

Thanks for the great work!

**Comment by bwbroersma** [comment]
Ok, actually the party name mapping between Almanak & Kiesraad still has to be loaded into production.

This is the province API call (not filtered on organization / function):
[`https://rest-api.allmanak.nl/v0/overheidsorganisatie?type=eq.Provincie&einddatum=is.null&naam=eq.Provincie+Noord-Holland&select=naam,ictucode,logo(url,backgroundcolor,license),website:contact-%3Einternet,organisaties(organisatie:organisatieid(naam,functies(functie:functieid(naam,medewerkers(persoon:persoonid(naam,partij))))))`](https://rest-api.allmanak.nl/v0/overheidsorganisatie?type=eq.Provincie&einddatum=is.null&naam=eq.Provincie+Noord-Holland&select=naam,ictucode,logo(url,backgroundcolor,license),website:contact-%3Einternet,organisaties(organisatie:organisatieid(naam,functies(functie:functieid(naam,medewerkers(persoon:persoonid(naam,partij)))))))

Remove the `&naam=eq.Provincie+Noord-Holland` to fetch all provinces. Note that currently only 3 provinces have Statenleden: Fryslân under `Organisatie: Provinciale Staten > Functie: Provinciale Staten`, Groningen under `Organisatie: Provinciale Staten > Functie: Lid` and Noord-Holland under organisatie `Provinciale Staten > Functie: Statenleden`.
We're working on a press statement to improve this extremely bad coverage.

**Comment by bwbroersma** [comment]
More name mappings can be found here:
https://github.com/openstate/almanak-kiesraad-matcher/blob/569caaed6d9b4c9d98ea8ae604096400062b6d57/import_data/ImportProvinceAlmanak.py#L49-L78

**Comment by jurrian** [comment]
> 4. For iBabs: decide whether to use iBabsPerson or the new allmanak (@jurrian?)

It could be very possible that iBabs uses iBabsPersons to reference who attended some meeting or voted on some motion, therefore those have preference. I would advise against importing them both separate since this would only create doubles and confusion. We could merge both sources but that might be difficult, and what will we do when one or the other is missing?

Lets start with iBabsPersons for now and maybe we can merge them with Allmanak persons in the future.

**Comment by voodoo-burger** [comment]
These changes are ready to be merged after review (#152).

There are some trade-offs regarding persons:

- Gender can not always be determined because not every person name includes the title ('Dhr.' or 'Mw.')
- Allmanak information does not appear to include email addresses
- Provinces have no persons yet. According to https://github.com/openstate/open-raadsinformatie/issues/134#issuecomment-498321750 OpenState will issue a press release to hopefully improve this

iBabs will continue to use IBabsPersonsExtractor for now.
