### ISSUE TITLE
Incorrect Agenda Item order in REST API

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#135]
The order of the agenda RDF List should mimic source data. Here's a [Meeting resource](https://id.openraadsinformatie.nl/266787.ttl) with an inaccurate agenda ([view in ori-search](http://ori.argu.co/?zoekterm=%22mogelijk%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F266787)).

Perhaps this problem happens during ETL (NEO4j?), perhaps it happens in @fletcher91's REST API.

**Comment by jurrian** [comment]
My guess is it happens in the REST API since it think it currently cannot handle blank nodes.

**Comment by joepio** [comment]
If that's true, then this issue should be ignored in the current Rails API, since it is about to be replaced with the [Event Sourced Kafka / NGINX one](https://github.com/ontola/ori_api).

**Comment by fletcher91** [comment]
This was fixed in https://github.com/ontola/ori_api/commit/2ea64774d5c5fe5f568805904e144319d84521dc
