### ISSUE TITLE
Decide how to use councils

### ISSUE THREAD

**Issue by voodoo-burger** [openstate/open-raadsinformatie#139]
Council extraction is currently broken and/or useless. Most sources except for GO currently don't use councils, and in GO they are automatically created during the creation of meetings, which is not the correct place.

To fix this I suggest writing a `MunicipalityCouncilExtractor` and a `ProvinceCouncilExtractor` that return these hard-coded objects:

> id: `gemeenteraad-{key}` or `provinciale-staten-{key}`
> name: `Gemeenteraad {sitename}` or `Provinciale Staten {sitename}`,
> collection: `gemeenteraad-{key}` or `provinciale-staten-{key}`

**Comment by jurrian** [comment]
After discussion with Joep we decided that council Organizations should only be created when they are provided by the supplier. We should try not to create new resources that do not exist in the suppliers system. Therefore, when a supplier has committees and a council, meetings should be attached to these Organizations. When they are not provided then meetings should attach directly to the municipality or province Organization. All council extractors that not follow this rule should be removed.

**Comment by voodoo-burger** [comment]
This will be fixed by #154 .
