### ISSUE TITLE
Add municipality/province ID to DeltaLoader

### ISSUE THREAD

**Issue by voodoo-burger** [openstate/open-raadsinformatie#141]
~~The DeltaLoader needs to know which index the item being loaded is related to. The easiest would be to add an `_index_name` key.~~

The DeltaLoader needs to know which municipality or province the item being loaded is related to. To do this, every item needs to get a new required field that refers to the top level municipality or province.

**Comment by jurrian** [comment]
Does this concern the Elasticsearch index? How will the data in the DeltaLoader relate to ES?
The celery task should hold information about the ES index, which is set in pipeline.py:56

**Comment by voodoo-burger** [comment]
Updates as of WIP pull request:

- Created a separate `TopLevelOrganization` model for municipality/province
- Added `has_organization_name` property to all other models (Committee, Organization [Party], Person, Member, Membership, Meeting, Attachment, MediaObject, etc.)

Sample ES output for Beemster is attached.
[beemster.txt](https://github.com/openstate/open-raadsinformatie/files/3248195/beemster.txt)
