### ISSUE TITLE
Filtering on date not working

### ISSUE THREAD

**Issue by patricksevat** [openstate/open-raadsinformatie#15]
Hi guys,

Been playing around with the API today and noticed that filtering using date is not working as described in the docs.

> Use the following format to filter on a date range:
```
{
   "date": {
      "from": "2011-12-24",
      "to": "2011-12-28"
   }
}
```

So I've tried this using [request](https://www.npmjs.com/package/request) and got this error:
`{ error: '\'date\' is not a valid filter', status: 'error' }`

Here's my code, seems like a simple fix (I've tried using "start_date" and "end_date") as well, but I don't feel like trial-and-error today ;). Plus might be helpful for others. Other filters that I have tried are working as expected.

```
var request = require('request');

var query = 'vergadering*+utrecht|amstelveen';

var bodyRequest = {
    "query": query, 
    "size": 10, 
    "filters": {
        "classification": {
            "terms": ["Agenda"]
        },
        "date": {
            "from": "2016-01-01",
            "to": "2016-12-31"
        }
    }
};

var options =
    {
        uri: 'http://api.openraadsinformatie.nl/v0/search',
        method: 'POST',
        json: true,
        headers: {
            "content-type": "application/json"
        },
        body: bodyRequest
    };

request(options, function (err, obj, json) {
    if (err) throw err;
    
    console.log(obj.body);
});
```

**Comment by breyten** [comment]
Ah, yeah I should update the docs a bit -- the main problem is that querying via the `/search` endpoint has actually fewer filters than the `/search/events` endpoint because not all objects have the `start_date` or `end_date` fields. You should be able to use the `start_date` filter on the latter endpoint (And indeed, not the `date` filter. Sorry! I'll fix the docs as soon as possible.

**Comment by patricksevat** [comment]
Hi breyten!

Thanks for the quick reply! Using `start_date` on `/search/events` did the trick, thank you!
