### ISSUE TITLE
Separate Neo4J into its own loader

### ISSUE THREAD

**Issue by jorritb** [openstate/open-raadsinformatie#153]
To respect separation of concerns and possibly to improve stability (as in #147) it might be a good idea to separate the Neo4J logic into its own loader.

**Comment by jurrian** [comment]
I think this might be hard. Consider for example that the Elastic loader is successfully executed first, and the new Neo4j loader comes after but raises a constraint error. That might lead to inconsistencies.

**Comment by jorritb** [comment]
This is no longer relevant since we are moving away from Neo4j.
