### ISSUE TITLE
Add SIMBestuur config

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#161]
SIM asked us to write an interface for SIMBestuur. @jorritb will start working on this. More information will be added soon.

**Comment by joepio** [comment]
Docs: https://simbestuur-test.mendixcloud.com/rest-doc/api

**Comment by jurrian** [comment]
What is the progress on this one @jorritb?

**Comment by jorritb** [comment]
There is an `issue-161-simbestuur` branch that has the work I've done on this so far. It's not a lot because it got stopped almost as soon as I started on it.
