### ISSUE TITLE
Use `pages` predicate for extracted text

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#165]
We currently use `schema:text` for extracted text.

Since this property is (sometimes) paginated, some of these properties are RDF lists, others are literals. This makes the API a bit unpredictable. A predicate should have a consistent datatype.

I suggest we create a new property: `meeting:pages`.
The definition is as follows:

The `pages` property contains an RDF Sequence of String literals that represents an ordered sequence of extracted plaintext, where each item in the array represents a page from the resource.

**Comment by joepio** [comment]
Perhaps even better is to have IRIs for every single page.

**Comment by jurrian** [comment]
Relates to #189

**Comment by jurrian** [comment]
I see that `schema:text` is currently serialized to an array. I remember in the past that this might have been different. Can you supply an example of both where this is happening?

**Comment by joepio** [comment]
We use `schema:text` as well for Meetings and AgendaItems, IIRC, where it's serialized as a string instead of a List / Array. However, this inconsistency is not that big of a deal. This is low-prio for now.
