### ISSUE TITLE
Stadsdelen should have unique names

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#167]
Currently, all the Amsterdam Stadsdelen organizations have the name "Amsterdam". These should be made more specific.

**Comment by jorritb** [comment]
This was fixed 2 weeks ago in https://github.com/openstate/open-raadsinformatie/commit/c10d6a7eca2eedf235da32304fa34e1b261cbfad, but municipalities and provinces are not re-extracted after the first time. @jurrian is going to re-run the municipality/province extraction which should fix this.

**Comment by jurrian** [comment]
Gtyj

**Comment by jurrian** [comment]
My phone closed this on its own

**Comment by jorritb** [comment]
@jurrian did you run the re-extraction of top-level municipalities/provinces? I'm not seeing the updates on some indexes.

**Comment by jurrian** [comment]
I did, but it seems that all municipalities/provinces gave Contraint Exceptions, so I guess that is why there are no updates.

**Comment by jurrian** [comment]
This is probably fixed by now in #175.
