### ISSUE TITLE
Add resource types and properties to documentation

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#168]
Currenlty, the [docs](https://github.com/ontola/ori-search/blob/master/docs.md) do not (link to or) describe the available set of classes and properties.

Ideally, these are generated from the models in the source code. Alternatively, they are described in some Markdown component.

**Comment by joepio** [comment]
Relates to #127

**Comment by jurrian** [comment]
Currently no priority.

**Comment by joepio** [comment]
We could refer to [the definitions](https://github.com/openstate/open-raadsinformatie/tree/master/ocd_backend/models/definitions) in the source. It provides a decent overview, including types.
