### ISSUE TITLE
Check missing orgaizations

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#169]
Searching for `classification: Province` shows only 2 resources, although 5 indexes exits.

**Comment by joepio** [comment]
Some municipalities also seem to lack an Organization document, such as Binnenmaas.

**Comment by jorritb** [comment]
This should be fixed now that we've switched to the ES Upsert loader (#160). We discovered a misconfiguration yesterday that was causing province runs to fail which should also be fixed now.
