### ISSUE TITLE
Missing text field in MediaObjects from provinces

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#171]
Perhaps the text enricher isn't running properly, or the documents are not supported.

example: https://id.openraadsinformatie.nl/273591

**Comment by jorritb** [comment]
The problem appears to be that some provinces are using PDF files that don't have (the correct) MIME headers. I will check to see if there is a way around that.

**Comment by jurrian** [comment]
Probably relates to #178

**Comment by joepio** [comment]
Closing this in favor of #288
