### ISSUE TITLE
DeltaLoader keeps hanging when service is not running

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#176]
Setting `KAFKA_SESSION_TIMEOUT` to 1 does not stop the DeltaLoader from hanging when there is no Kafka service in development.

**Comment by jorritb** [comment]
That's why I suggested #148 ;)

**Comment by jurrian** [comment]
Yes, but I don't think we should force running Kafka. If it's not running we can skip it in development.

**Comment by jorritb** [comment]
I thought issues were supposed to be closed automatically when the related pull request is merged...

**Comment by jurrian** [comment]
They do when they are merged in the default branch, which is master. Another option is to use the 'close' or 'closes' keyword instead.
