### ISSUE TITLE
Add OWMS 4.0 IRIs to municipalities

### ISSUE THREAD

**Issue by rescribet** [openstate/open-raadsinformatie#177]
Link the municipalities to their official IRI's from the [OWMS](http://standaarden.overheid.nl/owms/terms)

**Comment by bwbroersma** [comment]
Note that OWMS is 4.0 and AKN is 5.0 (but not all municipalities have 5.0 resource identifiers yet).
I also see that the `resourceidentifiers` in the Allmanak API are wrapped in a double array, will probably fix that in `v1` this week.

**Comment by jurrian** [comment]
Wontfix for the time being. It will not be picked up soon, but is a good suggestion for later.
