### ISSUE TITLE
Add municipality Harderwijk and others missing 

### ISSUE THREAD

**Issue by monty241** [openstate/open-raadsinformatie#182]
Tested with several local municipalities. No documents were found. For instance “Harderwijk kadernota” returns no relevant documents but the data is available on Ibabs.

**Comment by joepio** [comment]
Harderwijk is not imported (both in v0 and the new v1 of the API). The [source](https://github.com/openstate/open-raadsinformatie/blob/master/ocd_backend/sources/harderwijk.json) file of Harderwijk points to CompanyWebCast, which is no longer supported in V1. 

Harderwijk does [seem to use iBabs](https://www.harderwijk.nl/organisatie/gemeenteraad_3187/).

We could add Harderwijk to the [iBabs sources file], but I'll need to check whether they've given permission.

**Comment by monty241** [comment]
Ok. Can I somehow assist in the process since there are many municipalities in this region missing ? I can make some labor available for an action. It is easier for me to do so instead of writing an alternative as a connector on Invantive sql.

**Comment by tomkunzler** [comment]
VNG will be scaling up Open Raadsinformatie with 100 extra municps this year. You can of course assist them by motivating the griffies of the municipalities in your region to subscribe. They can send a message to sander.bakker@vng.nl and you can share this info page with them: https://www.vngrealisatie.nl/producten/open-raadsinformatie

It may be helpful to say that participating will be free and it will cost them no more time then to mail to Sander and their software supplier to apply. Some software suppliers charge a small amount for opening up the API. It also helps to tell them that due to the upcoming Wet open overheid sharing raadsinformatie as open data will become mandatory in the future.

**Comment by monty241** [comment]
Text used (Dutch):

Geachte griffie,

Als burger hecht ik veel waarde aan een transparant beleid en uw gemeente doet dat ook. Toch is het voor mij tijdrovend om kennis te nemen van de raadsstukken als een onderwerp over talrijke vergaderingen heen gaat. Laat staan als het een onderwerp is dat in meerdere gemeentes speelt. Als techneut kom je dan een end met wat geknutsel, maar andere burgers kunnen dat niet.

Ik ben blij dat Open State Foundation en VNG samen de toegankelijkheid van de raadsstukken verbeteren door ze toegankelijk te maken via https://openraadsinformatie.nl. Ook bereidt u zich daarmee al voor op de Wet open overheid (Woo).

Verzoek

Ik zou het fijn vinden als uw gemeente hier ook aan meedoet door een mail te sturen aan Sander Bakker van VNG (sander.bakker@vng.nl) met als onderwerp “Onze gemeente wil deelnemen aan openraadsinformatie”. 

Meer informatie hierover staat op https://openraadsinformatie.nl, die doorlinkt naar de VNG-site.
Ik heb begrepen dat opname gratis is en dat de tijdsinspanning niet groter is dan het sturen van een e-mail aan Sander en uw softwareleverancier die de raadsstukken online aanbiedt. Sommige softwareleveranciers schijnen een kleine vergoeding te vragen voor het openzetten van het koppelvlak (zogenaamde “API”).

Mag ik u rekenen op uw hulp om zo de transparantie te vergroten?

**Comment by monty241** [comment]
Alle gemeentes in Limburg en Gelderland die nog niet er in zitten aangeschreven.

**Comment by monty241** [comment]
In ocd_backend/sources/ori.ibabs.yaml staan Nijmegen en Harderwijk, maar beiden staan nog niet op productie lijkt het. Ik weet hoe dat effectief wordt, maar misschien deployment issue?

**Comment by jorritb** [comment]
Voor Nijmegen zijn er 767 resultaten: http://ori.argu.co/?zoekterm=%22*%22&organisaties=[%22ori_nijmegen_20190809125121%22] . Dit zijn vooral personen dus het is qua inhoud inderdaad nog wat mager.

**Comment by joepio** [comment]
Lijkt alsof er maar 1 vergadering op 9 januari is geimporteerd

https://ori.argu.co/?zoekterm=%22*%22&organisaties=%5B%22ori_nijmegen_20190809125121%22%5D&type=%5B%22MediaObject%22%5D&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F17414

**Comment by monty241** [comment]
Ik was weer eens lekker wollig. Ik liep al vast bij de lijst van gemeentes: zowel Harderwijk als Nijmegen ontbreken in dit plaatje:
![image](https://user-images.githubusercontent.com/7579444/63505374-baa48b00-c4d3-11e9-8111-87644ab919a4.png)

**Comment by jorritb** [comment]
We hebben op dit moment 2 versies draaien: v0 op zoek.openraadsinformatie.nl en v1 op ori.argu.co . De screenshot komt van v0, die heeft inderdaad minder gemeenten dan v1. We zijn op dit moment bezig om te kijken of v1 inmiddels op hetzelfde niveau zit als v0 qua data quality en quantity (#146), en als dit zo is wordt v1 de nieuwe standaard en zal v0 (waarschijnlijk) uit de lucht gehaald worden.

**Comment by monty241** [comment]
OK, thx. Ori.argu.co werkt ook weer. Ik zag wel een certificaatissue:

![image](https://user-images.githubusercontent.com/7579444/63674925-f26b4580-c7e7-11e9-98aa-b0589507c972.png)

Ik kan vrijwel nog geen stukken van Nijmegen en Harderwijk vinden op de ori.argu.co., dus ik stel voor om issue open te houden.

**Comment by joepio** [comment]
Hmmm, die HTTPS hebben we juist laatst [gefixed](https://github.com/ontola/ori-search/issues/4). 

![Selection_048](https://user-images.githubusercontent.com/2183313/63675574-66f2b400-c7e9-11e9-9547-3107b3688f4a.png)

Werkt een hard refresh (ctrl+ shift + r)? Kan je de details van het certificaat weergeven?

**Comment by jorritb** [comment]
HTTP requests naar ori.argu.co worden nog niet geupgrade naar HTTPS, daar zal ik een redirect voor toevoegen.
