### ISSUE TITLE
Advanced resource entity implementation

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#184]
`entity` is used to designate the origin of a resource. Different resources can been derived from one entity, i.e. a [meeting](https://api.notubiz.nl/events/meetings/470736?format=json&version=1.10.8) has multiple nested documents. ~~These documents can be resolvable by their own URL but the original source of the resource is still the same `entity`. The same as its parent since this is our actual source.~~ **Resources that *can* be resolved (have their own identifier) should use that URL instead, see the comment below.**

However, some resources can be enriched. A document can be downloaded and process by a enricher, this changes the original source of the document and this should be reflected in `entity`. This should be implemented.

**Comment by jurrian** [comment]
Some extra explanation: `entity` should identify the resource as accurate as possible. If possible, it should be identified with a URL, scheme and query parameters [like this](https://api.notubiz.nl/events/meetings/39488?format=json&version=1.10.8). However, sometimes the URL might contain sensitive information like authentication.

The golden rule is to specify how one could best try to locate the resource. In SOAP it is not possible to use URL's to identify a specific resource, in that case we do not have more information than the identifier itself so `entity` would be like '8984124' and `entity_type` would be SOAP.

`used_file` is an URL to our cached version of the current resource, there is an **important relation** between `entity` and `used_file`:

- When an URL links directly to a resource, `entity` and `used_file` should reflect that same resource.
- When there is no way to directly link to the resource (i.e. when one URL contains multiple resources which do not have their own URL's). `entity` will identify the resource inside the `used_file`.

**Comment by jorritb** [comment]
`used_file` saving on GCS still needs to be implemented, so I'm adding this to the 1.3.2 milestone for now.

**Comment by jurrian** [comment]
Moved to wiki as documentation: https://github.com/openstate/open-raadsinformatie/wiki/Advanced-resource-entity-implementation
