### ISSUE TITLE
Enter key changes municipality selector to All.

### ISSUE THREAD

**Issue by monty241** [openstate/open-raadsinformatie#187]
Reproduction:
* Go to http://zoek.openraadsinformatie.nl/#/search.
* Type 'Governance' in search box (no enter).
* Check out all municipalities.
* Select "Aalsmeer".
* Add '2' to 'Governance'.
* Press enter key.
* All checkboxes are set before the municipalities.

Expectation:
* Pressing enter does not reset the chosen municipalities.

**Comment by joepio** [comment]
Since we will switch to the new front-end soon ([ori-search](https://github.com/ontola/ori-search/)), this won't be fixed in the old search engine.
