### ISSUE TITLE
Fix certificate.

### ISSUE THREAD

**Issue by monty241** [openstate/open-raadsinformatie#188]
See picture, taken using Chrome production release:

![image](https://user-images.githubusercontent.com/7579444/62723510-30f3b880-ba11-11e9-805f-b6953d6e8f88.png)

**Comment by jurrian** [comment]
Thanks for notifying us, I saw there was a problem with the cert but it changed 5 min later. Everything looks fine now.
![A44BC443-A958-479B-8607-4AF1C94D9149](https://user-images.githubusercontent.com/177496/62724579-a06aa780-ba13-11e9-9d32-8283ada12dc5.jpeg)

**Comment by monty241** [comment]
Thx, fixed.
