### ISSUE TITLE
Missing indexing by search engines.

### ISSUE THREAD

**Issue by monty241** [openstate/open-raadsinformatie#189]
The documents and metadata contained on open raadsinformatie are not indexed by Google. For instance, the following search query returns no relevant results despite "Maastricht" having all of it proceedings listed:

![image](https://user-images.githubusercontent.com/7579444/62727659-3acde980-ba1a-11e9-87db-394a19d94b2f.png)

**Comment by joepio** [comment]
This is a really interesting problem. We might need server side rendering of Resource views and PDF views to do this. 

@fletcher91 do you think SSR support for Link-Redux in the foreseeable future is likely?

**Comment by fletcher91** [comment]
We basically already do that in Argu, everything is SSR'ed but we only include the meta tags in the initial response, not the fully rendered DOM (due to issues).

That app is much, much more complicated. SSR for this project seems a lot more reasonable (Bar the PDF rendering of course).

**Comment by monty241** [comment]
Can't you just provide a dynamically generated sitemap to the original URLs, possibly with a proxy and correct lastmod date to reduce load on backend?

**Comment by joepio** [comment]
Backend load is not a problem, I think, but the crawler of Google might be. It needs content, which needs to be rendered to HTML. That's why we probably need server side rendering.

**Comment by jurrian** [comment]
@joepio is this an issue for ori-search instead?

**Comment by joepio** [comment]
Agreed, closing here. Issue moved to ori-search: https://github.com/openstate/open-raadsinformatie/issues/189
