### ISSUE TITLE
Unable to merge: No resource found for predicate

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#193]
Getting a lot of the following errors, seems to happen for almost every municipality:

```
W 2019-08-09T13:30:59.870022524Z Unable to merge: No resource found for predicate "collection" with value "hendrik-ido-ambacht-D66" in column "prop_string" 
W 2019-08-09T13:31:00.095437172Z Unable to merge: No resource found for predicate "collection" with value "hendrik-ido-ambacht-E.V.A." in column "prop_string" 
W 2019-08-09T13:31:01.003863047Z Unable to merge: No resource found for predicate "collection" with value "hendrik-ido-ambacht-Gemeente Belangen" in column "prop_string"
W 2019-08-09T13:32:05.254565309Z Unable to merge: No resource found for predicate "collection" with value "leeuwarden-CDA" in column "prop_string" 
W 2019-08-09T13:32:07.602375102Z Unable to merge: No resource found for predicate "collection" with value "leeuwarden-D66" in column "prop_string" 
W 2019-08-09T13:32:07.767480109Z Unable to merge: No resource found for predicate "collection" with value "leeuwarden-FNP" in column "prop_string"  
```

**Comment by jorritb** [comment]
This is  a problem with the names of parties in the Allmanak not being consistent between views.

Compare for Hendrik-Ido-Ambacht:

Parties: https://rest-api.allmanak.nl/v0/overheidsorganisatie?systemid=eq.33795&select=zetels
Persons: https://rest-api.allmanak.nl/v0/overheidsorganisatie?systemid=eq.33795&select=naam,functies(functie:functieid(naam,medewerkers(persoon:persoonid(systemid,naam,partij))))&functies.functie.naam=eq.Raadslid

In the parties view one of the party names is SGP/Christenunie while in the persons view it is (sometimes) SGP-Christenunie.

@bwbroersma @breyten is there a solution for this?

**Comment by jurrian** [comment]
Haven't seen this error in ages, closing for now.
