### ISSUE TITLE
AttributeError: Ori Identifier is not present

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#195]
## Error in ori

**AttributeError** in **ocd_backend.loaders.elasticsearch.elasticsearch_upsert_loader**
Ori Identifier is not present, has the model been saved?

[View on Bugsnag](https://app.bugsnag.com/argu/ori/errors/5d4d71720d8c760019b11faf?event_id=5d4d7e9e004cc726de070000&i=gh&m=ci)

## Stacktrace

    models/model.py:164 - get_ori_identifier
    models/model.py:169 - get_short_identifier
    models/serializers.py:343 - ori_uri
    models/serializers.py:290 - serialize_prop
    models/serializers.py:330 - serialize_prop
    models/serializers.py:65 - deflate
    models/serializers.py:320 - serialize
    loaders/elasticsearch.py:94 - load_item
    loaders/__init__.py:28 - start
    loaders/elasticsearch.py:29 - start
    loaders/elasticsearch.py:136 - elasticsearch_upsert_loader

[View full stacktrace](https://app.bugsnag.com/argu/ori/errors/5d4d71720d8c760019b11faf?event_id=5d4d7e9e004cc726de070000&i=gh&m=ci)

*Created by Jurrian Tromp via Bugsnag*

**Comment by jorritb** [comment]
I can't find a cause for this at the moment. It's probably related to the enrichers hanging (#204) so I'm going to look at this issue again after that is handled.

**Comment by jurrian** [comment]
An error linked to this issue has been reopened in Bugsnag
[**AttributeError** in **models/model.py:164**](https://app.bugsnag.com/argu/ori/errors/5d4d71720d8c760019b11faf?event_id=5d5d4efd004d63d8b9630000&i=gh&m=eu)

**Comment by jorritb** [comment]
This seems to be caused by postgres having too many connections and not being able to provide a new ID.

**Comment by jurrian** [comment]
An error linked to this issue has been reopened in Bugsnag
[**AttributeError** in **models/model.py:164**](https://app.bugsnag.com/argu/ori/errors/5d4d71720d8c760019b11faf?event_id=5d6cfc2e004e6e346aa30000&i=gh&m=eu)

**Comment by jurrian** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**AttributeError** in **ocd_backend.transformers.ibabs_meeting.meeting_item**](https://app.bugsnag.com/argu/ori/errors/5d4d71720d8c760019b11faf?event_id=5d7fac9b004fcee182cc0000&i=gh&m=fx)

**Comment by jurrian** [comment]
Seems to be fixed for now.
