### ISSUE TITLE
PDF conversion should be separated from item loading

### ISSUE THREAD

**Issue by breyten** [openstate/open-raadsinformatie#2]
PDF conversion now happens in the item transformers fro each separate information system. This could be enhanced by extracting this process and provide it's own item transformer.

Benefits:
- Events are searchable before all the PDFs have been extracted
- PDF extraction can be done separately from event indexing

There should be an extractor which finds the events to index from the frontend. Also, for performance reasons we should write a different loader which updates existing records.

**Comment by jurrian** [comment]
Has been already been implemented somewhere.
