### ISSUE TITLE
Votable items should be stored as Motion entities - not Events

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#20]
The Popolo specification has a special ['Motion'](www.popoloproject.com/specs/motion.html) class, but this is currently not used by Open Raadsinformatie (ORI). Currently, motions are accessible as events ([example](http://api.openraadsinformatie.nl/v0/overbetuwe/events/9c3c5f8b05bc3937f689d91638682584424115c9)). I suggest adding a new 'Motion' Class to ORI for all the votable objects.

**Comment by breyten** [comment]
Yes! This has actually been pretty much all of my work in the past two weeks :D -- See https://github.com/openstate/open-raadsinformatie/tree/motions_improvements (Which also implements the vote_events class, but is not live yet). When this goes live we'll remove these events

**Comment by jurrian** [comment]
Seems like this has been fixed already some time ago.
