### ISSUE TITLE
Split events in event items

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#21]
Currently, (at least some) of the event data is lost in the Utrecht dataset. For example, [here](http://api.openraadsinformatie.nl/v0/utrecht/events/aeebc986b44b42df5ab8ee4c311a415a20ae7eff) you see that the request returns a list of sources (documents). These sources do not specify for which event item they are relevant. The [source of the information](http://player.companywebcast.com/gemeenteutrecht/20140410_1/nl/player) does show these links, which shows that this information is present. 

Currenty, the various agenda items are displayed in the description as header items. I think these event items should be different objects, each with their own documents. Also, these items can have a certain duration.

A meeting consists of various agenda items. These agenda items each have a certain duration, title, description and documents.

I suggest adding an 'agenda_item' object that has:
- A title string (optional)
- A description string (optional)
- A start_datetime and an end_datetime (or perhaps a duration) (optional)
- An array of documents and motions (items on which can be decided and or voted)
- A parent event id (required)
- An index integer which represents the position in the array of agenda items (required)

I know this is not how popolo deals with it, but it seems to be a schema that makes a lot of sense for how government meetings tend to be structured. 

EDIT: I submitted this [issue to the Popolo github page](https://github.com/popolo-project/popolo-spec/issues/121).

**Comment by jurrian** [comment]
This is fixed in V1.
