### ISSUE TITLE
Add province Groningen

### ISSUE THREAD

**Issue by jorritb** [openstate/open-raadsinformatie#214]
They use Notubiz; https://groningen.stateninformatie.nl/ .

**Comment by tomkunzler** [comment]
I don't recall the province of Groningen in giving final permission to add their data to Open Stateninformatie. They still have it in consideration. @joepio right?

**Comment by joepio** [comment]
I assumed they agreed like the others, but you're right, they haven't yet. Let's wait for formal permission.

**Comment by tomkunzler** [comment]
I will remind them to see if they have made a decision.

**Comment by joepio** [comment]
I did the same a couple of minutes ago!

**Comment by jurrian** [comment]
Update?

**Comment by joepio** [comment]
Not yet

**Comment by jurrian** [comment]
Can this be closed?

**Comment by jurrian** [comment]
Please reopen if Groningen has given permission.

**Comment by joepio** [comment]
Heard from @baksand that Groningen has given green light!

**Comment by joepio** [comment]
Added the source file. @robvandijk can you run the import when you've got it running?

**Comment by robvandijk** [comment]
@joepio import seems to be finished - can you check the results?

**Comment by joepio** [comment]
Yes!

https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22osi_groningen_20241112110011%22%5D
