### ISSUE TITLE
Postgres Deadlocks

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#224]
## Error in ori

**sqlalchemy.exc.OperationalError** in **models/postgres_database.py:130**
(psycopg2.errors.DeadlockDetected) deadlock detected
DETAIL:  Process 457892 waits for ShareLock on transaction 7531314; blocked by process 457950.
Process 457950 waits for ShareLock on transaction 7531318; blocked by process 457892.
HINT:  See server log for query details.
CONTEXT:  while deleting tuple (6878,16) in relation "property"

[SQL: DELETE FROM property WHERE property.resource_id = %(resource_id_1)s AND property.predicate IN (%(predicate_1)s, %(predicate_2)s, %(predicate_3)s, %(predicate_4)s, %(predicate_5)s, %(predicate_6)s, %(predicate_7)s, %(predicate_8)s, %(predicate_9)s)]
[parameters: {'predicate_1': 'http://schema.org/isBasedOn', 'predicate_3': 'http://www.w3.org/2006/vcard/ns#hasOrganizationName', 'predicate_2': 'http://schema.org/fileSize', 'predicate_5': 'http://schema.org/contentUrl', 'predicate_4': 'http://schema.org/dateModified', 'predicate_7': 'http://purl.org/dc/terms/isReferencedBy', 'predicate_6': 'http://schema.org/name', 'predicate_9': 'http://schema.or...

[View on Bugsnag](https://app.bugsnag.com/argu/ori/errors/5d5d4ef43852fe001acb644d?event_id=5d62a197004dd37810c70000&i=gh&m=ci)

## Stacktrace

    models/postgres_database.py:130 - save
    models/model.py:216 - save
    enrichers/media_enricher/__init__.py:83 - enrich_item
    enrichers/__init__.py:36 - start

[View full stacktrace](https://app.bugsnag.com/argu/ori/errors/5d5d4ef43852fe001acb644d?event_id=5d62a197004dd37810c70000&i=gh&m=ci)

*Created by Jorrit van Belzen via Bugsnag*

**Comment by jorritb** [comment]
I will try tweaking the `lock_timeout` and `deadlock_timeout` settings. But this probably has to do with enrichers being slow (#204) so that might not solve it.

**Comment by jurrian** [comment]
No deadlocks have been logged for over a week, closing for now.
