### ISSUE TITLE
iBabs import error, possible API change

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#229]
@jorritb can you add info? If a changing API of iBabs is at fault, try to find out what caused it and if there is an LTS version of their API. If there is none, perhaps we can work out something that helps prevent this.

**Comment by jorritb** [comment]
Rond begin juli werd ineens de `User-Agent` header verplicht waardoor SOAP connecties niet meer werkten (omdat wij geen `User-Agent` header mee gaven). Dit was toen gefixed door wel de header mee te geven. Hier zijn we toen achter gekomen na uren testen met Postman en alle headers 1 voor 1 vergelijken.

Rond half augustus werkte dit ook niet meer en zijn we geswitched naar een SOAP client met een `HttpTransport` in plaats van een `HttpAuthenticatedTransport` (omdat iBabs geen authenticatie gebruikt). Dit heeft ongeveer een paar dagen gewerkt tot nu zonder code veranderingen aan onze kant op iedere request vanuit de client in de python code een `403 Forbidden` terug komt.

De WSDL is in de browser wel gewoon bereikbaar (https://www.mijnbabs.nl/iBabsWCFService/Public.svc?singleWsdl) maar via de code die wij gebruiken niet:

```            
self.client = Client(ibabs_wsdl,
                     port='BasicHttpsBinding_IPublic',
                     transport=HttpTransport(),
                     timeout=10,
                     headers={'User-Agent': settings.USER_AGENT})
```

We gebruiken [`suds-community`](https://github.com/suds-community/suds) als SOAP client. We zijn overgestapt van de originele suds (die niet langer ontwikkeld wordt) naar community omdat die support heeft voor request headers. In de tussentijd hebben we ook nog [`zeep`](https://github.com/mvantellingen/python-zeep) geprobeerd maar die bleek niet compatibel.

**Comment by joepio** [comment]
Reactie iBabs:

```
Zou hun client niet om kunnen gaan met die WAF rule die er https://wcf.ibabs.eu/api/Public.svc van maakt?
Als ik in SoapUI een test aanmaak met https://www.mijnbabs.nl/iBabsWCFService/Public.svc?singleWsdl
En vervolgens de “Alive“ aanroep zie ik dat het netjes verandert naar ons echte endpoint maar of onderstaande opensource tooltjes dat ook doen??
 
Dus laat het hun eens proberen met https://wcf.ibabs.eu/api/Public.svc?singleWsdl
```
