### ISSUE TITLE
Vote_event without an actual vote

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#23]
It appears that some vote_events do not contain any _votes_, _group_results_ or _counts_ as specified by the popolo standard.

For example, the following motion has been withdrawn and therefore has not been voted on: 
http://api.openraadsinformatie.nl/v0/utrecht/motions/1a8ffb25f6cafc1ad1c735d1053ebd96947eb896

However, it has a vote_event which doesn't say much since there was no vote:
http://api.openraadsinformatie.nl/v0/utrecht/vote_events/1a8ffb25f6cafc1ad1c735d1053ebd96947eb896

Is this by design?

**Comment by breyten** [comment]
I suppose the best way to describe it is accidental design ;) It seems a bit odd, but one advantage is that you just can get the entire list of motions+votes in one go (We do use it in the search interface) regardless if there was an actual vote or not. Going to the motions endpoint first would require you to do at least one extra request.

But what would you guys prefer?

**Comment by jurrian** [comment]
It would be logical that only actual vote_events will be shown as such.
Empty vote_events could be omitted since they give the impression that votes have been cast while that's not the case.
Therefore, motions+votes could be served if both are available. If there is no real vote_event then only the motions will be shown, without the empty vote_events.
I guess this way doesn't require an extra request, does it?
