### ISSUE TITLE
Add Wijchen Druten

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#230]
I believe both use iBabs. We have OK from VNG. Let Sander Bakker know when they are added.

**Comment by jurrian** [comment]
Both Druten and Wijchen are invalid Sitename's in iBabs. Could it be that they are combined into another name?

**Comment by joepio** [comment]
I've asked ibabs for the names

**Comment by joepio** [comment]
Naam is wdw

**Comment by jurrian** [comment]
What I suspected. They have been added now for the v1.3.6 release.

**Comment by jurrian** [comment]
There appeared to be a problem with the iBabs whitelist, should be fixed now.
