### ISSUE TITLE
Enable organization selector - Add ES index label to organisation resources

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#234]
I want to provide a UI in ori-search where users can select their municipality / province and instantly see all most recent / future meetings. I should be able to query the organizations endpoint, and find the relevant elasticsearch index.

Since municipalities and provinces have unique indexes in Elasticsearch, I might be able to use this. I suggest that we add the elastic index label (as much as easily doable) to the organization resource as a property.

**Comment by breyten** [comment]
You can get a list of munucipalities from the command line like this:

```
curl 'https://api.openraadsinformatie.nl/v1/elastic/_search' -H 'Content-type: application/json' -d ' {
        "size": 500,
        "query": {
            "bool": {
                "must": {
                    "match_all": {}
                },
                "filter": {
                    "terms": {
                        "classification": ["municipality", "province"]
                    }
                }
            }
        }
    }'
```

Also, when getting results back from Elasticsearch, you can find the index in the `_index` property. See `https://api.openraadsinformatie.nl/v1/elastic/_search?size=1` (The above query has this property too, by the way)

**Comment by joepio** [comment]
Thanks for the quick reply. The ES way that you suggest works fine, and it is what I use in the filters for ori-search, but I'd prefer to use the REST organizations endpoint + a link-redux view.

However, maybe your way is quicker. It means I'll just create a stateful react component that does some `fetch`ing.

[Related issue in ori-search](https://github.com/ontola/ori-search/issues/61)

**Comment by joepio** [comment]
I've solved it using @breyten's approach!
