### ISSUE TITLE
Problem resolving person_id's in memberships

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#24]
There seems to be a problem resolving the person_id's in the memberships.

For example, this event has several memberships in the associated organization:
http://api.openraadsinformatie.nl/v0/utrecht/events/4ec7de05dfdb04a179a0786b2dee6ca0f547cfee

This is one of these memberships:

```
        "area": {
          "name": ""
        }, 
        "id": "41084ddae2fe837c4e093e6ef949b32c", 
        "label": "Raadslid", 
        "organization": {
          "classification": "Council", 
          "id": "gemeente-utrecht-utrecht-ut", 
          "name": "Gemeente Utrecht (Utrecht) (UT)"
        }, 
        "organization_id": "gemeente-utrecht-utrecht-ut", 
        "person_id": "c0e4dfb4023782e26046729ea2b280f7322bc1ab", 
        "role": "Raadslid"
```

When I try to resolve the person_id, I get a "Document not found" error.
I also tried the id but that doesn't work either.

**Comment by breyten** [comment]
Hmm that is definitely a bug. I'll try to think of a solution.

**Comment by jurrian** [comment]
Should be solved now in V1.
