### ISSUE TITLE
Missing extracted pages

### ISSUE THREAD

**Issue by aolieman** [openstate/open-raadsinformatie#242]
For some reason not all pages from pdf documents seem to be extracted. In the examples I've seen, the missing pages are always those at the end of the document.

Here's a good example in which the document has 32 pages, but only the first 20 are present in the `text` array:
https://api.openraadsinformatie.nl/v1/elastic/ori_harden*/_search?pretty&q=_id:13455

For HierOverheid, we're targeting definition lists which are usually located near the end of the document (in an appendix). We keep finding documents which mention such an appendix in the table of contents, but where the text extracted from the corresponding pages is missing.

**Comment by joepio** [comment]
We'll up the page limit to 100
