### ISSUE TITLE
Bug in results Leiderdorp, possibly more municipalities

### ISSUE THREAD

**Issue by Taluke** [openstate/open-raadsinformatie#247]
Today I noticed in bug in a document from Leiderdorp in ORI. And some research learned that probably all Leiderdorp-documents fail: https://storage.googleapis.com/ori-static/https:/www.raadleiderdorp.nl/api/v1/meetings/1588/documents/37265. I don't know if this is a Leiderdorp specific problem or if there are more municipalities with the same problem.

**Comment by jurrian** [comment]
Can you give me the URL where this is referenced?

**Comment by Taluke** [comment]
- https://app.1848.nl/document/ori-item/5883?qs=leiderdorp
OR:
- http://ori.argu.co/?zoekterm=%22leiderdorp%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F29721

**Comment by joepio** [comment]
The `schema:contentUrl` value is missing, but the `schema:isBasedOn` is present and seems to resolve.

However, if I recall correctly, the [isBasedOn URL](https://www.raadleiderdorp.nl/api/v1/meetings/1584/documents/37200) didn't resolve the previous time I tried. Not sure about this, though.
