### ISSUE TITLE
id endpoint has different data than elasticsearch endpoint

### ISSUE THREAD

**Issue by breyten** [openstate/open-raadsinformatie#248]
Requesting https://id.openraadsinformatie.nl/106069.jsonld leads to a 404 error, while https://api.openraadsinformatie.nl/v1/elastic/_search?q=_id:106069 returns the data

**Comment by fletcher91** [comment]
I can confirm that delta's for this resource have been put on the ori-delta bus, so the resource should have been indexed already.

**Comment by fletcher91** [comment]
The new service is reindexing all the events. If all goes well, the api (id.openraadsinformatie.nl) should be consistent again in about a day

**Comment by joepio** [comment]
Fixed!
