### ISSUE TITLE
Add Rozendaal 

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#249]
They use ibabs and they've given permission.

I'll notify sander when it's merged.

**Comment by jurrian** [comment]
`iBabsWCFService has no access to site Rozendaal!` seems that we don't have been given permission.

**Comment by joepio** [comment]
I've asked sander to contact Rozendaal

**Comment by jurrian** [comment]
@joepio any update here?

**Comment by joepio** [comment]
I've asked for an update again

**Comment by jurrian** [comment]
Will be part of #309.
