### ISSUE TITLE
Utrecht meetings are not being imported

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#250]

**Comment by joepio** [comment]
Wijchen, too? (might be related, might be separate issue)

**Comment by jurrian** [comment]
Unrelated, Wijchen is not found where Utrecht is.

**Comment by Taluke** [comment]
I see that Utrecht is being imported now. Are these also the Utrecht reports? Or just meetings? And I see something goes wrong with persons. 1000hits with 'geen naam'.

**Comment by jurrian** [comment]
At the moment only meetings but the reports will probably follow soon. I see no persons without name, do you have an example?
