### ISSUE TITLE
Company Webcast child events

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#26]
I have noticed that the Company Webcast events do not have children events specified.
It appears that these events _do_ have event items as can be seen here:
[http://player.companywebcast.com/gemeenteutrecht/20160407_1/nl/player](url)

Instead the agenda is put as a blob in de description attribute:
[http://api.openraadsinformatie.nl/v0/utrecht/events/d1a914084c8af5b787d0fbe439d51e3bd2c801e4](url)

Maybe it would be more logical if the event would have the agenda items als children events.
This would also help to identify which source belongs to which agenda item.

Another thing, the classification "Videotulen Gemeenteraad" doesn't say much about the object, wouldn't it be wise to name it "Agenda" of "Agendapunt" like the rest?

**Comment by jurrian** [comment]
CWC is currently not used, closing for now.

**Comment by breyten** [comment]
Isn't CWC used in Utrecht?

**Comment by jurrian** [comment]
That seems indeed to be the case, I will see if it still works in V1.
