### ISSUE TITLE
Overijssel missing

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#260]
The source is present, but it's not available in the (elastic) API. Can you check this out @jurrian ?

note to self: notify Tom

**Comment by jurrian** [comment]
Seems to be (maybe partially) related to #255

**Comment by jurrian** [comment]
The other issue seems to be #257, which has already been solved but not yet pushed to production. Overijssel was the only one affected.

**Comment by jurrian** [comment]
Over the period of 2019, at this moment 83 meetings have been indexed and a total of 376 items have been indexed. Closing this issue.
