### ISSUE TITLE
DeltaLoader KafkaError MSG_SIZE_TOO_LARGE

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#267]
## Error in ori

**KafkaException** in **ocd_backend.loaders.delta.delta_loader**
KafkaError{code=MSG_SIZE_TOO_LARGE,val=10,str="Unable to produce message: Broker: Message size too large"}

[View on Bugsnag](https://app.bugsnag.com/argu/ori/errors/5d89cf6cd98e0a0019425866?event_id=5d8cc72700503e586a610000&i=gh&m=ci)

## Stacktrace

    loaders/delta.py:53 - load_item
    loaders/__init__.py:28 - start
    loaders/delta.py:72 - delta_loader

[View full stacktrace](https://app.bugsnag.com/argu/ori/errors/5d89cf6cd98e0a0019425866?event_id=5d8cc72700503e586a610000&i=gh&m=ci)

*Created by Jurrian Tromp via Bugsnag*

**Comment by jorritb** [comment]
This seems like a possible solution: https://stackoverflow.com/a/21343878/384925 .

**Comment by fletcher91** [comment]
Unless a single statement will hit this limit, the delta can be split (per statement) without causing problems.
