### ISSUE TITLE
GO API v2 missing documents for Utrecht, Flevoland

### ISSUE THREAD

**Issue by Taluke** [openstate/open-raadsinformatie#269]
Hi, I did some searchwork to see how complete ORI is with documents from the provinces. Limburg, Zuid Holland and Noord Holland appear to be OK, but Utrecht, Overijssel and Flevoland are far from complete. Flevoland and Utrecht have a few 'vergadering' items, but no 'documenten'. The import of documents from Overijssel appear to have stopped since june.

EDIT: Some more research learns that more documents appear to fail, also from the provinces that seem relatively complete at first sight. For example, this document from Zuid Holland gives an error: https://staten.zuid-holland.nl/dsresource?objectid=9cc731bb-a0a7-4544-becd-67a878752c9e (Notulen Statenvergadering 4 september 2019)

**Comment by jurrian** [comment]
I've updated the comparison in #146 and indeed it shows that quite a few municipalities/provinces are not complete. Especially iBabs municipalities are lagging and we are trying to close the gap. I will let you know when there data available in V1.

**Comment by joepio** [comment]
Utrecht is still lacking documents.

**Comment by jurrian** [comment]
The link in the first post now gives a 404. There has been a great improvement in the completeness of meetings, which are currently indexed until 2012. Can you supply some specific examples of resources that are still missing? I am closing this for now but don't hesitate to reopen if you have some examples that we can check.

**Comment by joepio** [comment]
Both Utrecht and Flevoland seem to be missing all documents:

https://openbesluitvorming.nl/search?zoekterm=%22*%22&organisaties=%5B%22osi_provincie-utrecht_20190809125121%22%2C%22osi_flevoland_20190809125113%22%5D

**Comment by jurrian** [comment]
This has to do with the difference between GO API V1 and V2. All municipalities currently use V1, provinces use V2 but most code is still the same. It seems that the GO transformer has never been adequately adjusted for V2 and has not been tested properly.

**Comment by joepio** [comment]
Breyten started work on the GO v2 extractor, but the transformers still require some work.

**Comment by joepio** [comment]
Jur sent mail to GO

**Comment by jurrian** [comment]
No response yet. I've sent another mail with some questions about the increased amount of requests that are needed in v2.

**Comment by joepio** [comment]
Still no response? If not, we might need to fall back on V1 - if that is possible, of course.

**Comment by jurrian** [comment]
GO support has responded on the question about the increased amount of requests:

> Hierbij het antwoord op je vraag: de conclusie klopt: je moet in API v2 alle objecten los van elkaar opvragen. Er is geen snellere manier. Er bestaat nu geen mogelijkheid om bij een vergadering direct ook alle agendapunten en documenten mee te krijgen. Daarmee is het aan de gebruiker van de API om hier verstandig mee om te gaan.

So I have announced that we will be reversing all GO entities to V1, they said that every GO entity should have both versions so it won't be a problem.

**Comment by joepio** [comment]
Fix is merged, but the data still has to be reprocessed. Expected later this week.

**Comment by jurrian** [comment]
Both provinces are currently being processed since 2000 to now.

**Comment by joepio** [comment]
Still missing: https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22osi_provincie-utrecht_20190809125121%22%5D

**Comment by jorritb** [comment]
There is an issue with ElasticSearch where the loader function that is supposed to iterate through all Models in a document is not searching deeper than 2 levels. I'm still trying to fix this.

**Comment by jorritb** [comment]
The loader issue appears to be fixed, currently importing from 1-1-2020, and will do a longer import after that.

**Comment by joepio** [comment]
Still no documents in Utrecht: https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22osi_provincie-utrecht_20190809125121%22%5D&type=%5B%22MediaObject%22%5D

**Comment by joepio** [comment]
However, Flevoland seems to work: https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22osi_flevoland_20190809125113%22%5D&type=%5B%22MediaObject%22%5D

**Comment by jurrian** [comment]
After a bug was fixed it seems that attachments are now being imported for Provincie Utrecht. Closing.
