### ISSUE TITLE
Contribution guidelines missing

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#27]
The [link to the contribution guidelines](https://github.com/openstate/open-raadsinformatie/blob/master/docs/dev/getting_started.rst) found in the readme results in a 404.

**Comment by joepsz** [comment]
We're currently working on some documentation for contributing.

**Comment by jurrian** [comment]
Link to [contributing](https://github.com/openstate/open-raadsinformatie/blob/master/CONTRIBUTING.rst) will be updated shortly.
