### ISSUE TITLE
Page snippet compatibility

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#287]
In ori-search, we'd love to be able to click on a document and open the corresponding page in the PDF viewer. This requires that Elastic knows in which page a word is mentioned. Currently, each page is a string in an Array. This should be a [nested datatype](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html).

@aolieman has some ideas on how to do this. 

Relates to #165.

**Comment by aolieman** [comment]
I've used this "sub-document in nested field" pattern in several projects. It introduces a bit of latency, but is certainly faster than string matching snippets against the full document `_source`.

Asking elasticsearch for [nested inner hits](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#nested-inner-hits) is easy. Getting the proper highlights/snippets for each nested object (i.e. page) is a bit more work, but not too much.

The cumbersome thing here is that multi-valued fields (currently used for pages) are implemented very differently than nested fields in the lucene data structures. They are mapping-incompatible, which means that one cannot reindex from the one type to the other within elasticsearch. Fresh indexes with an updated mapping for `text` would have to be created and filled with normal http requests, so requires a bit of code to be written to read from the old-mapping indices and write to the ones with the new mapping.

It's too bad that we cannot use elasticsearch's internal reindexing mechanism, which is many times faster and more resource efficient then having to read & write via the API. The good news is that the time investment to write migration code is minimal.. it's mostly just the longer wait that is disappointing.
