### ISSUE TITLE
Missing text fields in MediaObjects

### ISSUE THREAD

**Issue by aolieman** [openstate/open-raadsinformatie#288]
I've found three kinds of issues with the current linked data.

MediaObject as `vcard:hasOrganizationName` of another MediaObject:

- https://id.openraadsinformatie.nl/251205
- https://id.openraadsinformatie.nl/252295

MediaObject without text:

- https://id.openraadsinformatie.nl/66785
- https://id.openraadsinformatie.nl/251205
- https://id.openraadsinformatie.nl/252295

Missing data for documents that are present in the search engine:

- https://id.openraadsinformatie.nl/444673
- https://id.openraadsinformatie.nl/452208
- https://id.openraadsinformatie.nl/436691
- https://id.openraadsinformatie.nl/436778
- https://id.openraadsinformatie.nl/220803
- https://id.openraadsinformatie.nl/411183
- https://id.openraadsinformatie.nl/218771
- https://id.openraadsinformatie.nl/218741

Resolved issues:

- [x] MediaObject as `vcard:hasOrganizationName` of another MediaObject
- [x] MediaObject without text
- [x] Missing data for documents that are present in the search engine

**Comment by joepio** [comment]
Wrong identifiers and missing items are discussed in #282 
The missing text in MediaObjects is a seperate issue, though.

**Comment by joepio** [comment]
5/8 of the missing data items are now resolving.

**Comment by joepio** [comment]
7/8

**Comment by jurrian** [comment]
In case of https://id.openraadsinformatie.nl/66785 it seems that the pdf URL returns a 404.
At this point only https://id.openraadsinformatie.nl/444673 seems to 404.

**Comment by aolieman** [comment]
Good progress guys!

I keep coming across missing texts for MediaObjects though, e.g.
https://id.openraadsinformatie.nl/34225

In this case the pdf url does resolve properly, but the missing `contentUrl` and/or `text` predicates seem to prevent the search frontend from loading the pdf in its viewer.
https://ori.argu.co/search?showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F34225

**Comment by joepio** [comment]
Interesting: the resource Alex mentions that lacks a text field, does not lack the text field in Elastic, it's only missing in ID:

https://api.openraadsinformatie.nl/v1/elastic/ori_*/_search?q=_id:34225

So the missing text fields might also be related to a kafka / linked delta issue (#285)

**Comment by jurrian** [comment]
I have processed https://id.openraadsinformatie.nl/444673 manually but it still does not appear in the API service, same for 34225. This is part of a general problem with the ORI API service, closing this one in favor of #310.
