### ISSUE TITLE
ori_api organization names missing

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#293]
Most Organizations in `ori_api` lack all information (most importantly the name). 

- Utrecht: https://id.openraadsinformatie.nl/98
- Oosterhout: https://id.openraadsinformatie.nl/19
- Krimpenwaard: https://id.openraadsinformatie.nl/68

However, some do resolve and have name data:

- Voorschoten: https://id.openraadsinformatie.nl/37
- Buren: https://id.openraadsinformatie.nl/36

Might be related to #160.

**Comment by jorritb** [comment]
It is indeed related to #160. Somewhere municipalities are being created with the wrong IRI and no properties.

**Comment by jorritb** [comment]
Municipalities have this problem because they are initially sent to Kafka correctly when extracting organizations:

```
<https://id.openraadsinformatie.nl/35350> <http://purl.org/dc/terms/description> "Doetinchem, Gaanderen, Wehl" <http://purl.org/linked-delta/replace?graph=https%3A//id.openraadsinformatie.nl/35350> .

<https://id.openraadsinformatie.nl/35350> <http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#categories> "Municipality" <http://purl.org/linked-delta/replace?graph=https%3A//id.openraadsinformatie.nl/35350> .

<https://id.openraadsinformatie.nl/35350> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Organization> <http://purl.org/linked-delta/replace?graph=https%3A//id.openraadsinformatie.nl/35350> .

<https://id.openraadsinformatie.nl/35350> <http://www.w3.org/2004/02/skos/core#prefLabel> "Gemeente Doetinchem" <http://purl.org/linked-delta/replace?graph=https%3A//id.openraadsinformatie.nl/35350> .

<https://id.openraadsinformatie.nl/35350> <http://www.w3.org/2006/vcard/ns#email> "gemeente@doetinchem.nl" <http://purl.org/linked-delta/replace?graph=https%3A//id.openraadsinformatie.nl/35350> .

<https://id.openraadsinformatie.nl/35350> <http://www.w3.org/2006/vcard/ns#url> "http://www.doetinchem.nl" <http://purl.org/linked-delta/replace?graph=https%3A//id.openraadsinformatie.nl/35350> .

<https://id.openraadsinformatie.nl/35350> <https://argu.co/ns/meta#collection> "doetinchem" <http://purl.org/linked-delta/replace?graph=https%3A//id.openraadsinformatie.nl/35350> .
```

But as soon as there is a resource that refers to the municipality a new nquad gets sent without any information:

```
<https://id.openraadsinformatie.nl/35350> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Organization> <http://purl.org/linked-delta/replace?graph=https%3A//id.openraadsinformatie.nl/35350> .
```

`replace` seems to imply that the resource is replaced with the new version that has less information.

**Comment by joepio** [comment]
[ld:replace](https://github.com/ontola/linked-delta/blob/master/README.md#ldreplace) should not remove the other triples, if I understand the spec correctly. This could very well be a bug in 
ori_api @fletcher91

**Comment by fletcher91** [comment]
> replace seems to imply that the resource is replaced with the new version that has less information.

That is `ld:supplant`, `ld:replace` only removes previous subject/predicate matches, so in this case all other `rdf:type` statements would be discarded.

The `ld:replace` implementation [is tested](https://github.com/ontola/ori_api/blob/master/src/test/kotlin/io/ontola/linkeddelta/ApplyDeltaTest.kt#L62), so has this been reproduced in isolation yet?

**Comment by jurrian** [comment]
Just for information, `ld:replace` has been implemented in the DeltaLoader in v1.3.5 released on 26-9-2019. Before that `ld:supplant` was used.

**Comment by jorritb** [comment]
@joepio looks like this is resolved?

**Comment by joepio** [comment]
About 80% seems to work, some are still missing (e.g. [Diemen](https://openbesluitvorming.nl/?zoekterm=%22hallo%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F1067502)). Closing for now, as #310 discusses the remaining 20%.
