### ISSUE TITLE
Wijchen missing from organizations selector 

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#294]
When selecting an organization on the homepage of [ori-search](https://zoek.openraadsinformatie.nl/), wijchen is not there. However, it is present in the organizations filter. The first one searches for organizations, the second one filters indexes. So the index is here, but the Organization is missing.

This may have something to do with Wijchen / Druten being on the same iBabs server. #230

**Comment by jurrian** [comment]
This was due to the missing municipality resource for Wijchen, somehow the municipality for Druten was already present. Note for next time: municipalities should be reprocessed when new municipalities are added.
