### ISSUE TITLE
More semantic counts naming

### ISSUE THREAD

**Issue by fletcher91** [openstate/open-raadsinformatie#3]
I came across the http://api.openraadsinformatie.nl/v0/sources endpoint, and was instantly confused with the naming of `organizations: 66, persons: 233`, where I expected an array of ID's to the associated people and organisations. 

Renaming these to `organisation_count` and `person_count` would better convey the meaning of the numbers IMHO.

**Comment by jurrian** [comment]
Might be changed using linked data later. Wontfix for now.
