### ISSUE TITLE
Docs link broken

### ISSUE THREAD

**Issue by VincentVW** [openstate/open-raadsinformatie#30]
Just to notify; the docs link is broken. 

http://docs.openraadsinformatie.nl/

**Comment by breyten** [comment]
Can you elaborate a bit more? Seems to be working on our end.

**Comment by VincentVW** [comment]
@breyten that's odd, on my IP I get the classic "Welcome to nginx! If you see this page, the nginx web server is successfully installed and working. Further configuration is required.... etc.". When I use a VPN I get the docs correctly.

**Comment by breyten** [comment]
Ah, thanks! Seems to be IPv6 related -- We forgot to tell nginx to listen to IPv6 addresses as well as IPv4 ;) A solution should be there soon! Thanks for alerting us :-)

**Comment by VincentVW** [comment]
Happy to be of help!

**Comment by breyten** [comment]
Fixed by removing the AAAA record for now; Should be permanently fixed once we have a nginx load balancer installed (for which we have a working config)
