### ISSUE TITLE
Invalid CORS header in resolver

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#308]
Prevents PDF files from being show in `ori-search`.

```
Access to fetch at 'https://api.openraadsinformatie.nl/v1/resolve/api.notubiz.nl/document/6681021' from origin 'https://openbesluitvorming.nl' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by jurrian** [comment]
curl -X OPTIONS -v \
  https://api.openraadsinformatie.nl/v1/resolve/api.notubiz.nl/document/6681021

Returns the following CORS headers:
```
< cache-control: private, max-age=0
< access-control-allow-origin: *
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
< access-control-expose-headers: *
```

I seen no multiple values '*, *' as mentioned in the error, but implemented a possible solution anyway: https://community.apigee.com/questions/4989/cors-error-header-contains-multiple-values-but-onl.html

**Comment by jurrian** [comment]
The problem was that both our nginx and google cloud added CORS headers, it explains the multiple values '*, *'. A change in the nginx config has solved the problem.
