### ISSUE TITLE
New municipalities

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#309]
- [x] IBABS | Rozendaal
- [x] iBabs | Leudal
- [x] iBabs | Oldebroek
- [x] Ibabs | Asten
- [x] iBabs | Molenlanden
- [x] iBabs | Vught
- [x] ibabs | Mook en Middelaar
- [x] Notubiz | Wijk bij Duurstede
- [x] Notubiz | Zaltbommel
- [x] Parlaeus | Apeldoorn
- [x] Ibabs | Vught
- [x] Notubiz | Nijmegen (staat er nu in voor ibabs, maar moet voor 2014-2018 Notubiz)

Update: Added to sources, not yet imported.

**Comment by joepio** [comment]
Alle configs voor de nieuwe gemeenten zijn toegevoegd. Ibabs en Parlaeus moeten nog wat dingen instellen. Parlaeus moet nog een token geven (hebben we contact over) en iBabs moet toestemming geven voor de betreffende temeenten, en eventueel een IP whitelist. Ik heb Sander gevraagd of hij contact met iBabs heeft gehad hierover.

**Comment by joepio** [comment]
ibabs & notubiz are notified, waiting for green light.

**Comment by joepio** [comment]
ibabs municipalities are opened

**Comment by jurrian** [comment]
Import has been started.

**Comment by jurrian** [comment]
Asten heeft geen publieke Meetings in iBabs.

**Comment by jurrian** [comment]
Import has been completed and the municipalities seem to be imported well.
