### ISSUE TITLE
Documents & meetings from 19th december missing - import halted?

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#320]
See https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22ori_haarlemmermeer_20190809125112%22%2C%22ori_amstelveen_20190809125129%22%2C%22ori_enschede_20190809125113%22%2C%22ori_gouda_20190809125124%22%5D&type=%5B%22MediaObject%22%5D

E.g. Haarlemmermeer, Enschede, Gouda seem to miss all items from (roughly) the 19th of december last year. I assume this goes for all imports.

**Comment by jurrian** [comment]
Best thing to do is probably process december and januari again for all iBabs and see if that solves the problem.

**Comment by joepio** [comment]
Errors with disk space in Elastic instance were to blame.

**Comment by jurrian** [comment]
Specifically, for documentation purpose: when Elastic hits the watermark threshold it can invoke a setting blocking writes for some indices. When the disk problem is fixed this setting still persists. It needs to be set to `'{"index.blocks.read_only_allow_delete": null}'`

**Comment by jurrian** [comment]
Processing has started again, if all is well the missing meetings and documents should be added in one or two days.

**Comment by joepio** [comment]
The import seems to have succeeded, and the API should be up to date again. Good job @jurrian @jorritb!
