### ISSUE TITLE
Leeuwarden no items from 2019-02, switch to iBabs

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#339]
https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22ori_leeuwarden_20190809125103%22%5D

maybe they changed meeting software?

**Comment by jorritb** [comment]
It appears they stopped using Notubiz in February 2019 and switched to iBabs: https://ris2.ibabs.eu/Calendar/Index/Leeuwarden .

**Comment by joepio** [comment]
They still have to open up their iBabs instance. I'll ask Sander to send their clerk a mail.

**Comment by joepio** [comment]
We're whitelisted, so the import can begin for iBabs.
