### ISSUE TITLE
Exception handling: how to deal with missing data?

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#35]
When importing data from (new) external sources, some attributes can be absent. This will often cause errors (for example when trying to get the first item of an undefined array), which in turn might cause the resource to not be imported at all. Examples of missing data are discussed in #33 and #29, but way more have occurred during development.

This is a problem that will keep popping up as long as we are going to add new sources and models. It is practically impossible to predict which data will be present in any data source. There are a couple of methods of dealing with this issue. I think we need to make a decision on how to deal with missing data in general.

One of the ways to deal with it, is to fail explicitly every time a piece of data is missing. Throw an error, and tell the developer that he needs to somehow add this data. However, this is problematic, since it required the developer to create data where there actually is none. 

Another way is just to use the `try` `except` pattern: just pass an empty string, object or array when the item is missing - [show example](https://github.com/openstate/open-raadsinformatie/commit/c7702eb2efbb208d0a0a8e889ba0a8bcf33d084e). This is what the [except-handling branch](https://github.com/openstate/open-raadsinformatie/commits/except-handling) aims to do. However, this may lead to missing data, which is perhaps just as bad as creating new data.

Perhaps there is a better way of dealing with this.

**Comment by jurrian** [comment]
In general we go for the second option when dealing with missing data. It is nearly impossible to have consistent attributes for all sources and we have to expect that sometimes things are not complete. In V1 we can specify in the models which attributes are required. And if they lack, the program will fail that item. In the future, (bugsnag) logging should help identifying which items failed.
