### ISSUE TITLE
Add Nunspeet and Horst aan de Maas 

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#352]
Both use notubiz and are opened.

Gemeente Nunspeet: 1762
Gemeente Horst aan de Maas: 273

Notify sander when import has finished

**Comment by jorritb** [comment]
Preliminary import from the last 2 weeks is complete. Note that the theme classifier is currently not working. Longer import will follow soon.

**Comment by jurrian** [comment]
Issues with import have been resolved. Both are currently being processed.

**Comment by jurrian** [comment]
They seem to be complete now.
