### ISSUE TITLE
IntegrityError constraint in SQLAlchemy

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#358]
## Error in ori

**sqlalchemy.exc.IntegrityError** in **ocd_backend.transformers.ibabs_report.report_item**
(psycopg2.errors.CheckViolation) new row for relation "property" violates check constraint "property_check"
DETAIL:  Failing row contains (9700ef87-d793-4ec4-bbe6-7a1736b14dba, 2297388, http://schema.org/creator, null, null, null, null, null, null, null, null).

[SQL: INSERT INTO property (resource_id, predicate, "order", prop_resource, prop_string, prop_datetime, prop_integer, prop_float, prop_url) VALUES (%(resource_id)s, %(predicate)s, %(order)s, %(prop_resource)s, %(prop_string)s, %(prop_datetime)s, %(prop_integer)s, %(prop_float)s, %(prop_url)s) RETURNING property.id]
[parameters: {'resource_id': 2297388, 'predicate': 'http://schema.org/creator', 'order': None, 'prop_resource': None, 'prop_string': None, 'prop_datetime': None, 'prop_integer': None, 'prop_float': None, 'prop_url': None}]
(Background on this error at: http://sqlalche.me/e/gkpj)

[View on Bugsnag](https://app.bugsnag.com/argu/ori/errors/5e46d739bc004f0019d65f24?event_id=5e698d7900580d18cad60000&i=gh&m=ci)

## Stacktrace

    models/postgres_database.py:151 - save
    models/model.py:235 - save
    transformers/ibabs_report.py:109 - report_item

[View full stacktrace](https://app.bugsnag.com/argu/ori/errors/5e46d739bc004f0019d65f24?event_id=5e698d7900580d18cad60000&i=gh&m=ci)

*Created by Jurrian Tromp via Bugsnag*

**Comment by jorritb** [comment]
I have temporarily some more elaborate error logging so we can see what the exception actually is in production.

**Comment by jorritb** [comment]
Found the issue. Another example of a property being present on an original item but set to `None`.
