### ISSUE TITLE
Import Amsterdam not updated

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#363]
1. https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22ori_amsterdam_20190809125033%22%5D 
1. Sort by new
1. No new items since the 19th - the imports are probably halted a couple of weeks before that.

**Comment by jorritb** [comment]
It looks like there haven't been any meetings after the 19th, probably due to coronavirus... I will keep an eye on the calendar and see if new meetings get imported when they happen.

**Comment by joepio** [comment]
There have been meetings: https://amsterdam.raadsinformatie.nl/vergadering/726964/13%3A30%20Corona%3A%20Technische%20sessie%2026-03-2020

So something else is going on, presumably

**Comment by joepio** [comment]
Resolved. Was probably the same disk issue as #367
