### ISSUE TITLE
Add midden-groningen

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#364]
https://bestuur.midden-groningen.nl/api/v2

GO (probably use api V1)

Notify sander when ready

**Comment by joepio** [comment]
https://bestuur.midden-groningen.nl/api/v1/meetings
```
{"code\"":"authorization_required","message":"Authorization required","description":"This endpoint requires authorization however no access token was supplied."}
```

Probably need to get in touch with GO

**Comment by jurrian** [comment]
GO has opened up the open data endpoints for midden-groningen.

Processing has started.

**Comment by joepio** [comment]
Documents are properly imported in ES, but not yet in REST API

**Comment by jurrian** [comment]
That problem will be processed in #365. Closing this one.
