### ISSUE TITLE
West-betuwe / midden groningen (go) documents not loaded

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#365]
https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22ori_west_betuwe_20200310145740%22%5D&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F2589866

and 

https://openbesluitvorming.nl/?zoekterm=%22hoe%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F2743334&organisaties=%5B%22ori_midden-groningen_20200409124249%22%5D

the schema:isBasedOn resolves correctly, and the text is extracted correctly too, but the resolver URL does not work:

https://api.openraadsinformatie.nl/v1/resolve/gemeenteraad.westbetuwe.nl/api//v1/meetings/37/documents/873

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>
No such object: ori-static/gemeenteraad.westbetuwe.nl/api/v1/meetings/37/documents/873
</Details>
</Error>
```

**Comment by jurrian** [comment]
I've found two problems, seemingly unrelated.

The [url](https://bestuur.midden-groningen.nl/api/v1/meetings/829/documents/12660) related to the second link returns a server error: ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION. This suggests that there is a server side problem for GemeenteOplossingen for some files. I will contact them.

Second, these last added GO API municipalities seem to have **no** documents in Google Storage:
- Bloemendaal
- West-betuwe
- Midden-groningen
- Stichtse vecht

Those are exactly the last 4 entries in the ori.go.yaml, suggesting that there has been a bug introduced in the GO transformer. Somehow, provincie Utrecht seems to be unaffected. I'll do some more investigating.

**Comment by jurrian** [comment]
Gemeente Oplossingen has responded that they will try to find out what happens and will eventually get back to me.

**Comment by jurrian** [comment]
Turns out the mentioned 4 plus oude ijsselstreek had trailing slashes which caused the problems. I have removed the slashes in the sources and restarted the processing starting from 2000. All should be complete again when processing is finished. The [first](https://api.openraadsinformatie.nl/v1/resolve/gemeenteraad.bloemendaal.nl/api/v1/meetings/430/documents/6420) documents have been added already.

**Comment by joepio** [comment]
Seems fixed in most, but not all: https://id.openraadsinformatie.nl/2751135.ttl. Might be a problem with delta loader, since many new items are missing. #367

**Comment by joepio** [comment]
All seem to resolve now. Closing.
