### ISSUE TITLE
Resources missing in ori_api

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#367]
These seem to be loaded correctly in Elastic, but not in ori_api:

https://id.openraadsinformatie.nl/2768985
https://id.openraadsinformatie.nl/2768986
https://id.openraadsinformatie.nl/2769467
https://id.openraadsinformatie.nl/2769468

Different Orgs, different types of resources. What's going on?

**Comment by joepio** [comment]
Seems to be only recent items that are missing. Loader not running? Kafka issue?

**Comment by fletcher91** [comment]
You can bet your house on the disk being full

**Comment by joepio** [comment]
We've moved to apex-rs as the API (hosted on id.openbesluitvorming.nl), and the issue is fixed there.
