### ISSUE TITLE
Convert Gemeente Groningen from Notubiz to GO

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#370]
New URL: https://gemeenteraad.groningen.nl/api/v2/

Latest import seems from march 2020.

**Comment by jurrian** [comment]
Import has been started.

**Comment by jurrian** [comment]
Due to another large import, this has been delayed. Status will be reported in a few weeks.

**Comment by jurrian** [comment]
ETA 2 weeks

**Comment by jurrian** [comment]
Processing of has started, should be done soon. However, bug #377 is likely affecting ori-api causing them not to appear in id.openraadsinformatie.nl. Elasticsearch will not be affected.

**Comment by joepio** [comment]
The ES parts seem fine, but the URLs themselves 404.

https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22ori_groningen_20190809125025%22%5D

**Comment by joepio** [comment]
scratch that - it might be a link issue. I'll create a separate one.
