### ISSUE TITLE
Merge duplicate municipality indexes

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#372]
Gemeente Groningen has recently changed to Notubiz. This resulted in two indexes: 

<img width="709" alt="Screenshot 2020-06-23 at 14 05 11" src="https://user-images.githubusercontent.com/2183313/85401665-b06f7500-b55a-11ea-993e-57fc24db9b1b.png">

Can these be merged?

**Comment by jurrian** [comment]
Somehow a double Municipality for midden-groningen was created in the `ori_groningen_20190809125025` index. Checked for wrong values in sources but everything seems to be fine. Double has been removed.
