### ISSUE TITLE
Add Kapelle, Alphen-Chaam, Altena

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#374]
All have approved and use Notubiz

Gemeente Kapelle: 597
Gemeente Alphen-Chaam: 2030
Gemeente Altena: 3423

**Comment by jurrian** [comment]
ETA 2 weeks

**Comment by jurrian** [comment]
Processing of has started, should be done soon. However, bug #377 is likely affecting ori-api causing them not to appear in id.openraadsinformatie.nl. Elasticsearch will not be affected.

**Comment by joepio** [comment]
Seems complete!
