### ISSUE TITLE
Add Drechtsteden GO gemeenten

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#376]
https://raad.alblasserdam.nl/api/v2
http://raad.hardinxveld-giessendam.nl/api/v2
https://raad.papendrecht.nl/api/v2/
https://drechtraad.drechtsteden.nl/api/v2/
https://gemeenteraad.hofvantwente.nl/api/v2/

Hendrik Ido Ambacht is nog niet online maar dat zal ook het volgende worden  https://raad.h-i-ambacht.nl/api/v2/

**Comment by jurrian** [comment]
Hendrik-Ido-Ambacht bestaat ook in Notubiz, moet die eruit?

**Comment by jurrian** [comment]
Processing of has started, should be done soon. However, bug #377 is likely affecting ori-api causing them not to appear in id.openraadsinformatie.nl. Elasticsearch will not be affected.

**Comment by joepio** [comment]
Papendrecht seems partially loaded (only 17 resources so far)

https://openbesluitvorming.nl/search?zoekterm=%22*%22&organisaties=%5B%22ori_papendrecht_20200721220958%22%5D&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F2935793

**Comment by joepio** [comment]
Ablasserdam also works: https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22ori_alblasserdam_20200717161423%22%5D&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F2917679
