### ISSUE TITLE
404s since 06-25 for REST requests

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#377]
Has the loader halted?

Some resources that 404: 

https://openbesluitvorming.nl/?zoekterm=%22*%22&datums=%5B1592658877667%2C1626516734386%5D&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F2857055

also 2871238, 2857993

Seems to be unrelated to the organization

**Comment by jurrian** [comment]
Is currently being investigated.

**Comment by jurrian** [comment]
Ori api service is out of inodes (again) but increasing the inodes has not solved the problem yet. As predicted the associated issues on this issue are imported in elastic but not in ori api.

**Comment by jurrian** [comment]
ORI API service has been listening to the wrong Kafka topic since we have been using `ori-delta-new` for a clean import. To be sure I have reset this topic to the beginning, to ensure everything for this service is processed again. Results should be there in a day to a few days.

**Comment by joepio** [comment]
All resources from the issue are resolving just fine now.
