### ISSUE TITLE
Many missing documents in Elastic - meow attack

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#379]
https://api.openraadsinformatie.nl/v1/elastic/_cat/indices?v

Most of the municipalities have little to no documents.

**Comment by joepio** [comment]
Probably caused by [Meow attack](https://www.bleepingcomputer.com/news/security/new-meow-attack-has-wiped-dozens-of-unsecured-databases/)... 

We'll try a backup.

**Comment by joepio** [comment]
Apparently, our public endpoint was closed just yesterday, right _after_ the attack...

Anyways, it should be fixed now.

**Comment by joepio** [comment]
The attack happened tuesdaynight 23:00, when 150GB was reduced to 3GB.

**Comment by joepio** [comment]
Snapshot is being restored as of now.

**Comment by joepio** [comment]
Fixed by @jurrian!

**Comment by breyten** [comment]
Can you please clarify the extent of the closing of the public endpoint?Only temporary? Is it still able to query or not? (The endpoint is used in 1848)

**Comment by joepio** [comment]
Sorry for the unclear (and alarming message): the publicly accessible endpoint (which is _designed_ to be public) will be kept public. The endpoint that was _not_ supposed to be public (which was opened temporarily) is closed again. As long as you're using api.openraadsinformatie.nl/v1/elastic, you're good to go.

**Comment by breyten** [comment]
Ah, check! Thanks! :)
