### ISSUE TITLE
404s at REST endpoint

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#380]
For many resources, we're getting 404s in the front-end.

https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22ori_groningen_20190809125025%22%5D&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F36837

Edit: this issue first seemed to occur with a small set of resources, but now it seems to affect most. Just [try a random word](https://openbesluitvorming.nl/?zoekterm=%22politie%22) and click on items:

**Comment by joepio** [comment]
This is one of the requests showing a 404:

<img width="1212" alt="Screenshot 2020-08-25 at 09 49 19" src="https://user-images.githubusercontent.com/2183313/91147280-56a13d80-e6b8-11ea-865d-5bc9bfffc544.png">

The first item is fetched from Apex (id.openbesluitvorming.nl/link-lib/bulk), which returns a single 404 statement. 

When clicking Retry, the item is fetched _again_ but this request is sent to id.openraadsinformatie.nl/someid and returns a 200 with nice contents. However, the component is not reloading.

So we have two issues: 

1. Apex has missing documents (the most important one!)
1. The refresh action sends a request to the wrong endpoint, and it does not refresh the view.

**Comment by jurrian** [comment]
We are currently investigating where the missing documents are.

**Comment by jurrian** [comment]
@fletcher91 will investigate the Apex-RS side to see where the documents are missing.

**Comment by fletcher91** [comment]
The resource in question (`36837`) is not currently present in the database.

I've sampled about a dozen resources from bus files ranging from 200kB to 140MB from different dates, all resources were present in the database and contained multiple properties.

Searching through all messages on the bus _did not_ result in the message in question (See below, command tested prior with a known working IRI).

Which brings me to believe it was never posted on the ori-delta-new channel

@jurrian It might be smart to [log here](https://github.com/openstate/open-raadsinformatie/blob/da142bfb78e0ef284e5864991582aed29966ae6a/ocd_backend/loaders/delta.py#L83) when succeeding to post a message as well. 

Was it running with debug logs enabled? If so, did you find [the log with the id](https://github.com/openstate/open-raadsinformatie/blob/da142bfb78e0ef284e5864991582aed29966ae6a/ocd_backend/loaders/delta.py#L78) in question?
If that's the case something very peculiar seems to be happening


Bus test results:
| Command | Result |
|-|-|
| `gsutil cat gs://kafka-sink/topics/ori-delta-new/year=2020/month=06/**/*.bin \| grep "<https://id.openraadsinformatie.nl/36837>"` | No results |
| `gsutil cat gs://kafka-sink/topics/ori-delta-new/year=2020/month=07/**/*.bin \| grep "<https://id.openraadsinformatie.nl/36837>"` | No results |
| `gsutil cat gs://kafka-sink/topics/ori-delta-new/year=2020/month=08/**/*.bin \| grep "<https://id.openraadsinformatie.nl/36837>"` | No results |
| `gsutil cat gs://kafka-sink/topics/ori-delta-new/year=2020/month=09/**/*.bin \| grep "<https://id.openraadsinformatie.nl/36837>"` | No results |
| `gsutil cat gs://kafka-sink/topics/ori-delta-new/year=2020/month=10/**/*.bin \| grep "<https://id.openraadsinformatie.nl/36837>"` | No results |

**Comment by jurrian** [comment]
We have started doing a full import starting at 01-01-2000 (like before) for all municipalities to refill Kafka `ori-delta-new` once again. Such a huge import is expected to take a few weeks. Progress will be monitored here.

**Comment by jurrian** [comment]
There appeared to be two cases causing the missing documents when sampling them:

### Case 1
Caused by the Kafka consumer not being reset, after resetting the pointer they were imported in Apex-RS.
The amount of missing documents was somewhat improved:

ORI API not found, before Case 1:   832    41.6%
ORI API not found, after Case 1:    551    27.5%

### Case 2
It appears some IDs were not processed at all in the latest "big run" (all from 2000). For example the IDs 2703689 and 770473. Whereas the Case 1 problems appeared in Google Cloud logs, the latter are nowhere to be seen. There is no trace, also in Bugsnag nothing comes up concerning these IDs.

One reason could be that the big run does not cover these anymore, they did in the past and therefore they remain in Elastic. However, the `ended_at_time` is often recent as 2020-03-19T08:30:13.478562 in the first example. That would not explain why a third is missing.

[Oldebroek](https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22ori_oldebroek_20191227220052%22%5D&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F2154513) is one municipality that seems to be entirely missing in Apex-RS but exists in Elastic. I've manually done a complete import since 2000 but even it still seems to be missing.

There could be a bug that's not showing in Bugsnag, but it may be more likely that there's some "practical reason" why Oldebroek is still empty. Maybe there is some configuration not in order.

Perhaps the only feasable way it to follow a few missing IDs here all the way through the ETL process to see where they strand.

**Comment by joepio** [comment]
If I'm understanding this correctly, most 404s in the API (which are available in search) have no longer anything to do with any issue between these two systems. They occur because some documents that were previously succesfully fetched from a source system are no longer properly importable, for any sort of reason(s).

I think its preferable to present a subset of all information over presenting an inconsistent, but bigger, set of information. This means that we should remove the items from elastic that are no longer properly importable. 

Items that 404 at this moment:

[zwolle, 2019](https://openbesluitvorming.nl/?zoekterm=%22amendement%22&organisaties=%5B%22ori_zwolle_20190809125022%22%5D&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F1819341)
[zwolle, 2018](https://openbesluitvorming.nl/?zoekterm=%22amendement%22&organisaties=%5B%22ori_zwolle_20190809125022%22%5D&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F2362523)
(seems like everything Zwolle from before 2020 404s).

[oss, 2013](https://openbesluitvorming.nl/?zoekterm=%22kater%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F1327446)
[enschede, 2019-05](https://openbesluitvorming.nl/?zoekterm=%22kater%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F258372) ([however enschede, 2019-02 does not 404?](https://openbesluitvorming.nl/?zoekterm=%22kater%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F2655650) )
[overbetuwe, 2017](https://openbesluitvorming.nl/?zoekterm=%22kater%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F579007)
[zaanstad, 2017](https://openbesluitvorming.nl/?zoekterm=%22kater%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F576016)
[lansingerland, 2019](https://openbesluitvorming.nl/?zoekterm=%22kater%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F2955827)
[limburg, 2013](https://openbesluitvorming.nl/?zoekterm=%22kater%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F2287569)
[zoetermeer, 2015](https://openbesluitvorming.nl/?zoekterm=%22kater%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F890487)
[amsterdam, 2019](https://openbesluitvorming.nl/?zoekterm=%22kater%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F52325)
[leiden, 2017](https://openbesluitvorming.nl/?zoekterm=%22kater%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F523766)
[oisterwijk, 2017](https://openbesluitvorming.nl/?zoekterm=%22hapjes%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F510989)
[Krimpen ad IJssel, 2018](https://openbesluitvorming.nl/?zoekterm=%22hapjes%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F281412)

**Comment by joepio** [comment]
A script by jurrian removed the missing items from elastic, so there are no more 404s at the endpoint
