### ISSUE TITLE
Add new gemeenten

### ISSUE THREAD

**Issue by baksand** [openstate/open-raadsinformatie#381]
iBabs series

•	Doesburg
•	Deurne
•	Eersel
•	Sint Anthonis ( icm CWC)
•	Dantumadiel ( icm CWC)
•	Sluis
•	Elburg
•	Beesel
•	Heiloo
•	Reusel de Mierden
•	Stadskanaal
•	Berkelland
•	Vlieland
•	Terschelling
•	Winterswijk

p.s. Dantumadiel waiting for whitelisting iBabs

Can be opened!

**Comment by joepio** [comment]
Impressive list!

**Comment by baksand** [comment]
still growing but not there yet :-)

**Comment by jurrian** [comment]
I mapped the following municipalities, please confirm correct:

Notubiz
• Doesburg 
• Deurne
• Dantumadiel
• Heiloo

iBabs
• Eersel
• Sint Anthonis
• Sluis
• Elburg
• Beesel
• Reusel de Mierden
• Stadskanaal
• Berkelland
• Vlieland
• Terschelling
• Winterswijk

**Comment by jurrian** [comment]
Import for the mentioned municipalities has started.

**Comment by joepio** [comment]
nice!

**Comment by jurrian** [comment]
I have assumed that there are 4 Notubiz municipalities, I will switch them to iBabs.

**Comment by jurrian** [comment]
The import for the four wrong municipalties has started, they are imported from iBabs.
