### ISSUE TITLE
Add nieuwe gemeenten

### ISSUE THREAD

**Issue by baksand** [openstate/open-raadsinformatie#383]
Notubiz series:

Westvoorne: 1435
Barendrecht: 791
Bergen (L): 2062
Hoogeveen - 572
Lochem - 1761
Neder-Betuwe - 1810
Oegstgeest - 1856
Helmond - 1949
Goes - 276
IJsselstein - 2542

Can be opened!

**Comment by jurrian** [comment]
Good work @baksand! They will be added soon. Any idea how many new municipalities will follow?

**Comment by baksand** [comment]
thanks, but no idea, hope all of them

**Comment by jurrian** [comment]
Import for these has started, processing should be done today or in a few days from now.
