### ISSUE TITLE
Link to installation guide doesn't work

### ISSUE THREAD

**Issue by ricosuave82** [openstate/open-raadsinformatie#384]
The link provided in the Readme, which should point to the installation and running instructions, doesn't work.

https://github.com/openstate/open-raadsinformatie/blob/master/docs/installation.rst

I'm unable to find any docs on how to run the API locally and how to execute some basic operations, like fetching data from iBabs (which is a relevant topic for me). Could you help?

**Comment by jurrian** [comment]
I will look for the documentation, I think it got lost somewhere along the way.

About iBabs I can tell you that you need to be IP whitelisted by them for it to work locally, without the whitelist I'm afraid you won't be able to retrieve anything. You can contact them on support@ibabs.eu

**Comment by ricosuave82** [comment]
Thanks a lot @jurrian, this is very helpful. I'm working on a small project, which should read data from a certain iBabs account and I am using your project as a great reference, hope you don't mind! There isn't that much information I could find about using iBabs' Wsdl, if you have any recommendations I'd be happy to hear.

I'll contact their support about the IP whitelisting, thanks for the tip!

**Comment by jurrian** [comment]
Sure, no problem! I suggest to use a GUI for exploring iBabs SOAP, we use SoapUI on Linux.

Best of luck with your project! Closing this for now, feel free te reopen or respond.
