### ISSUE TITLE
Add new iBabs gemeenten (Ameland, T-Diel, Voerendaal)

### ISSUE THREAD

**Issue by baksand** [openstate/open-raadsinformatie#386]
iBabs series:

•	Ameland 
•	T-Diel
•	Voerendaal

thanks !

**Comment by jurrian** [comment]
For T-Diel I assumed the ibabs sitename will be Tytsjerksteradiel, but I kept "T-Diel" as name in ORI.

**Comment by baksand** [comment]
please also use Tytsjerksteradiel in ORI

**Comment by jurrian** [comment]
T-Diel has been renamed to Tytsjerksteradiel.

Import for these has started, processing should be done today or in a few days from now.
