### ISSUE TITLE
Towards Linked data: sensible, human IRI generation & routes

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#39]
In order to upgrade the quality of the data that this project outputs (and make it more RESTful), we should have a decent strategy for creating sensible, linkable identifiers ([IRI's](https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier)) for resources. 

Currently, ORI creates UUIDs. These are unique strings, e.g. `86763efa750946acf795cc5f6f18babb7b8a1a26`, but they don't link to anything. That means that the ID does not adhere to [Linked Data](https://www.google.nl/search?q=w3c+linked+data&oq=w3c+linked+data&aqs=chrome..69i57j0l5.2605j1j7&sourceid=chrome&ie=UTF-8) standards, since seeing just the ID does not tell you where you can find the resource; you need to understand how the API works in order to find it.

Since the resource is currently available at `http://api.openraadsinformatie.nl/v0/noordoostpolder/events/86763efa750946acf795cc5f6f18babb7b8a1a26`, we could use that as an IRI. However, this has other downsides. Firstly, the route includes a version number for the API. Versioning your API is sensible, of course, but linking it to your data is not a good strategy, since IRI's need to be permanent. Secondly, it's very long, which makes it hard to write down or share. Thirdly, reading it does not really help humans.

I suggest generating the iri's using the most relevant attribute, such as an internal identifier, a label or a name from the data, and excluding the data that is not relevant. The former example might become `http://openraadsinformatie.nl/noordoostpolder/events/raadsvergadering-2015-02`. 

The URI for a person might become `http://openraadsinformatie.nl/amstelveen/persons/E-Van-Der-Waal` instead of `http://api.openraadsinformatie.nl/v0/amstelveen/persons/85ea5414d7e9babdd101401e4527c42d904ecc8f`

Of course, when we make a change like this, it will be a breaking one and will need to be discussed thoroughly.

What are your thoughts on this? Does this seem like a good strategy?

**Comment by jurrian** [comment]
This is sometimes already the case: i.e. `http://api.openraadsinformatie.nl/v0/utrecht/organizations/gemeente-utrecht-utrecht-ut` however the versioning problem applies here as well. Maybe namespacing could help here, making it something like `ori:/utrecht/organizations/gemeente-utrecht` or `org:gemeente-utrecht`

**Comment by jurrian** [comment]
In V1 all public available identifiers are specified like: `http://id.openraadsinformatie.nl/123`. We chose not to include any other information like organization name or such, as this contextual information might change. For example, what if a woman marries and doesn't use her maiden name anymore? That would change the identifier. Keeping one unique id for every resource solves this problem.

In the future we could think of a system that would for example resolve `http://api.openraadsinformatie.nl/amstelveen/persons/E-Van-Der-Waal` to `http://id.openraadsinformatie.nl/123`, however the identifier will always be leading as it will be permanent.
