### ISSUE TITLE
Email of persons should be personal

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#4]
Some email addresses of persons are generic for the organisation (e.g. info@example.com). Since many applications tend to use email addresses as identifiers, I suggest leaving out the email address if it is not unique and personal. The [Popolo Project Spec](http://www.popoloproject.com/specs/person.html) does not require including an email, so that should not be a problem.

This issue appeared at the very least in [councilmen of Amstelveen](http://api.openraadsinformatie.nl/v0/amstelveen/persons/85ea5414d7e9babdd101401e4527c42d904ecc8f), [councilmen of Heerde](http://api.openraadsinformatie.nl/v0/heerde/persons/5e65745137ee7fa5e17778694dc0d1d99a3dbba1), [councilmen of Utrecht](http://api.openraadsinformatie.nl/v0/utrecht/persons/96fc1fc83c6d33b029bc6de0c8f8124b9dbc1392) and [the Clerk of Overbetuwe](http://api.openraadsinformatie.nl/v0/overbetuwe/persons/6faef4c0c82b5e24055e3cbdafd3f861c51405ce).

**Comment by jurrian** [comment]
It is the task of supplier systems to supply the correct email addresses. We could filter 'info@' and 'gemeente@' but it is not sustainable to find out what all the organizations use as generic email address.
