### ISSUE TITLE
Imports halted since 18-2-2021

### ISSUE THREAD

**Issue by tomuijtdehaag** [openstate/open-raadsinformatie#402]
I've started using your API recently, today I noticed that it seems like no new documents are being imported since 18-2-2021. Based on the issues on this Github page it looks very similar to what is discussed in #320 and #321. 

Are you aware of this/working on a fix?

**Comment by joepio** [comment]
Hi Tom,

Great that you're using the API! I wasn't aware of the import being stopped, so thanks for sharing that. To be honest, at this moment we don't have a customer / Service Level Agreement, so this project isn't top priority.

However, we'll look into this. I'll get back to this in one week.

**Comment by joepio** [comment]
Is probably caused by free disk storage running out. Let's try making that a tad bigger.

**Comment by joepio** [comment]
Upped the storage for postgres, and the service seems to be running again. The next daily run should probably import the items for past month, but to be sure I'll have to manually run an import job for 2021-02-18 to now.

I'll check back on this next week after the first imports have run.

**Comment by joepio** [comment]
Started a manual run, everything seems to be running correctly.
