### ISSUE TITLE
Faulty or unprocessable PDF crashes celery worker with SIGSEGV

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#42]
When celery processes a faulty PDF it results in a:
`WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).`

This is now becoming a pattern and causes celery to stop transforming the item.
All other PDF's from that item are therefore lost as well since the item will not be stored.

**Comment by jurrian** [comment]
Catching the SigSegv and recovering the transformation seems impossible.

One solution is to process the PDF's separate from the item. When a PDF causes a crash, the item and all other PDF's will still be processed. Although this solution needs to cope with race conditions.

**Comment by breyten** [comment]
* Is it possible to dteermine if the sigsegv happend with poppler or the other one we use? (I forgot the name :P)
* Perhaps it would be better to look at PDF parsing as enrichments (But not sure if they can fix this)

**Comment by jurrian** [comment]
I am pretty sure that Poppler is responsible for the sigsegv.

What happens when a sigsegv is detected is that celery marks the item as failed and restarts the worker, so this issue doesn't block other items. But still, missing items is not so nice..

Indeed, when the PDF's are processed separately as enrichments, one missing PDF would be better than missing an entire item.

The best scenario would be that the data would show something like "PDF appeared to be unprocessable" but that would require to catch and recover.

**Comment by breyten** [comment]
Wondering how much you would be able to change by modifying https://github.com/openstate/open-raadsinformatie/blob/master/ocd_backend/mixins.py a bit ;)

**Comment by jurrian** [comment]
Processing the enrichments after processing the main item? Good thinking!

**Comment by jurrian** [comment]
Further debugging with gdb resulted in more insight in why poppler crashes:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff2238687 in TextWord::getColor (b=<optimized out>, g=<optimized out>, r=<optimized out>, 
    this=<optimized out>) at poppler_src/poppler/TextOutputDev.h:174
174	poppler_src/poppler/TextOutputDev.h: No such file or directory.
```

This might suggest that Poppler crashes when when a PDF contains coloured text.
I've not confirmed this yet.

**Comment by jurrian** [comment]
PDF's with coloured texts don't necessarily seem to fail.
More debugging info about what goes wrong in the getColor method:
```
#0  0x00007ffff69d94e7 in TextWord::getColor (b=<optimized out>, g=<optimized out>, r=<optimized out>, 
    this=<optimized out>) at /usr/include/poppler/TextOutputDev.h:174
#1  __pyx_pf_9pdfparser_7poppler_4Line_4_get_text (__pyx_v_self=<optimized out>) at pdfparser/poppler.cpp:8555
#2  __pyx_pw_9pdfparser_7poppler_4Line_5_get_text (__pyx_v_self=<optimized out>, unused=<optimized out>)
    at pdfparser/poppler.cpp:8319
#3  0x00007ffff69dad62 in __Pyx_PyObject_CallMethO (arg=0x0, func=<optimized out>) at pdfparser/poppler.cpp:12073
#4  __Pyx_PyObject_CallNoArg (func=<optimized out>) at pdfparser/poppler.cpp:12098
#5  0x00007ffff69db1b8 in __pyx_pf_9pdfparser_7poppler_4Line_2__init__ (__pyx_v_block=<optimized out>, 
    __pyx_v_self=0x7ffff7eef4b0) at pdfparser/poppler.cpp:8245
#6  __pyx_pw_9pdfparser_7poppler_4Line_3__init__ (__pyx_v_self=0x7ffff7eef4b0, __pyx_args=<optimized out>, 
    __pyx_kwds=<optimized out>) at pdfparser/poppler.cpp:8122
#7  0x00005555556410b4 in ?? ()
#8  0x00007ffff69dc153 in __Pyx_PyObject_Call (kw=0x0, arg=0x7ffff7eace10, 
    func=0x7ffff6be7d40 <__pyx_type_9pdfparser_7poppler_Line>) at pdfparser/poppler.cpp:11933
#9  __pyx_pf_9pdfparser_7poppler_5Block_4__next__ (__pyx_v_self=0x7ffff7f530b0) at pdfparser/poppler.cpp:3824
#10 __pyx_pw_9pdfparser_7poppler_5Block_5__next__ (__pyx_v_self=0x7ffff7f530b0) at pdfparser/poppler.cpp:3764
#11 0x000055555564f970 in PyEval_EvalFrameEx ()
#12 0x000055555564d4e5 in PyEval_EvalCodeEx ()
#13 0x0000555555654e99 in PyEval_EvalFrameEx ()
#14 0x000055555564d4e5 in PyEval_EvalCodeEx ()
#15 0x000055555564d289 in PyEval_EvalCode ()
#16 0x000055555567d13f in ?? ()
#17 0x0000555555678032 in PyRun_FileExFlags ()
#18 0x0000555555677b7e in PyRun_SimpleFileExFlags ()
#19 0x0000555555628a02 in Py_Main ()
#20 0x00007ffff78123f1 in __libc_start_main (main=0x555555628330 <main>, argc=2, argv=0x7fffffffda38, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffda28)
    at ../csu/libc-start.c:291
#21 0x000055555562822a in _start ()
```

**Comment by jurrian** [comment]
This problem does not seem to appear anymore, not sure if it is fixed or that it just doesn't happen. Closing for now, reopen if it occurs again.
