### ISSUE TITLE
Docker Initialization of cloned repo is missing initial redis configuration

### ISSUE THREAD

**Issue by tsaltena** [openstate/open-raadsinformatie#431]
After a `docker compose up` of the entire stack, it appears redis is missing the required configurations refered to in the commandline. E.g.:

```
127.0.0.1:6379> select 0
OK
127.0.0.1:6379> keys _*
1) "_kombu.binding.loaders"
2) "_kombu.binding.enrichers"
3) "_kombu.binding.celery.pidbox"
4) "_kombu.binding.transformers"
127.0.0.1:6379> select 1
OK
127.0.0.1:6379[1]> keys _*
(empty list or set)
```

Upon attempting an import, this provides errors like so:
```
/opt/ori $ python manage.py extract process all
No settings found in redis for _all.*
/opt/ori $ python manage.py extract process ori.ibabs.utrecht
Redis sources found but non match the modus ori.ibabs.utrecht
/opt/ori $ python manage.py extract process all --source_path=ori.ibabs.utrecht
No settings found in redis for _all.*
/opt/ori $ python manage.py extract process start --source_path=ori.ibabs.utrecht
Redis sources found but non match the modus start
```

We would like to create a local copy for some of the connections and municipalities to test PDF parsing options and additional NLP-driven enrichtments such as Named Entity Recognition. 

As a quick fix, is it possible to share the redis dumpfile of the production instance? (it's in the named volume `redisdata`)

**Comment by joepio** [comment]
Thanks for sharing, @tsaltena, I'll send you a backup of the redis conf in production.

**Comment by joepio** [comment]
I've sent you a `backup.rdb` file!

**Comment by tsaltena** [comment]
Excellent, this works! (You do need to up the redis version to at least >5 in the .env accompanying the docker compose). 

Looks like the database also needs seeding... Could you also send me a
`pg_dump -U postgres -s ori > ori_scheme.dump`  ?

**Comment by tsaltena** [comment]
The schema can also be reconstructed using the sqlalchemy definition:

```
from sqlalchemy import create_engine
from ocd_backend.models.postgres_models import Base
engine = create_engine('postgresql://{user}:{pw}@postgres:5432/ori')
Base.metadata.create_all(engine)
```

requires adding a missing parenthesis to line 46:
https://github.com/openstate/open-raadsinformatie/blob/01a28593432d4038b9211877d54d75ef355d43de/ocd_backend/models/postgres_models.py#L46

and maybe some small direct queries to postgres (creating the database, enabling the uuid.v4 function, creating a user and permissions etc).

**Comment by joepio** [comment]
I believe this is no longer needed @tsaltena please re-open if I misremembered!
