### ISSUE TITLE
Graph database for more reliable linked data

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#44]
More complex data sources like the Dutch Parliamentary data source named Gegegevensmagazijn (GGM) need a more reliable way to save linked data. Currently document data is stored in Elasticsearch, during the ETL process linked objects are resolved using the ocd_frontend interface. This poses some problems:

1. Resources need to be processed in a certain order. E.g, if a meeting is processed but the corresponding  organisation hasn't, the program will fail or at least be incomplete.
2. Sometimes relations between items are not described in the raw input. E.g, if a meeting(item) has a relation to a vote_event but the motion that should be in-between is not referred by the meeting, there is no easy way to resolve the relation between that motion and the meeting.
3. Often it occurs that a data supplier is referencing a resource that isn't available, or worse, doesn't exist. We shouldn't copy references that are faulty, however currently there is no way of knowing.
4. The ocd_frontend interface queries Elasticsearch but the current implementation is not efficient and creates some considerable overhead.

To circumvent this, I would like to propose a way to save all (linked) data in a Graph database. This makes enables us to do quick database lookups to see which items are related. When serializing a document to for example Json-LD, we can consult the Graph in order to know which resources are related. Solving the problems mentioned above would make the project more reliable for challenges to come.

Therefore, Elasticsearch has to be substituted by a database which enables Graph querying. Some possible candidates which pro's and con's:

1. Elasticsearch with X-pack Graph plugin. Pro: probably the easiest implementation, little rewriting. Con: requires a license for X-pack which is really quite expensive.
2. ArangoDB. Pro: I do already have substantial experience with AQL, the query language.
3. Neo4J. Pro: Most referred to for python.

Elasticsearch will still be used for search but not as internal database system.

The adoption of these new technologies might fundamentally change the structure or development cycles of the project. Therefore, I would like to receive some feedback in order to make a well-considered decision.

**Comment by akuckartz** [comment]
:+1:

Please consider using an Open Source triplestore with support for SPARQL. Lists containing a few potential alternatives:
https://en.m.wikipedia.org/wiki/List_of_subject-predicate-object_databases and https://en.m.wikipedia.org/wiki/List_of_SPARQL_implementations

**Comment by joepio** [comment]
When selecting a NOSQL / graph database, keep the following in consideration:

Requirements:
- The technology should be open source to prevent vendor lock in.
- It should work with linked data

Nice to haves:
- Having a decent built-in reasoner is pretty coll
- Preferably, a non proprietary query language (e.g. SPARQL) should be compatible. This enables us to switch to a different storing technology later on.
- Compatibility with some sort of search solution, since we are going to replace elastic

**Comment by jurrian** [comment]
We eventually went for Neo4j which seems [by far the most popular option](https://db-engines.com/en/ranking/graph+dbms) of this moment. Neo4j offers the Cypher and Gremlin query languages and the possibility for REST and serialization, for example to RDF. SPARQL is not supported out of the box, but can be installed using a plugin.
Elastic will still be there for search purposes but Neo4j will be the main database.

**Comment by akuckartz** [comment]
Let us know your experiences with using that SPARQL plugin for Neo4j.
