### ISSUE TITLE
ORI API does not seem to be import meetings and documents

### ISSUE THREAD

**Issue by wessies** [openstate/open-raadsinformatie#443]
Hi all, 

I am using the ORI api and the the imports failed for meetings and documents. As an example for the municipality Leidschendam-Voorburg: 

https://api.openraadsinformatie.nl/v1/elastic/ori_leidschendam-voorburg_20230706020916/_search?q=MediaObject&sort=last_discussed_at:desc

Does give the last update on 2023-07-28 with attachment  "Dossier 3380 voorblad.pdf". However there are many new updates in the council meetings and documents. This also goes for the other municipalities. 

Could you have a look at this? 

Many many thanks from a happy user. 

BR Wesley

**Comment by joepio** [comment]
Bit late, but... It seems to work now!

https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22ori_fixed_leidschendam-voorburg_20230706020916%22%5D
