### ISSUE TITLE
Add new iBabs + notubiz Waterschappen!

### ISSUE THREAD

**Issue by baksand** [openstate/open-raadsinformatie#447]
please add :

- Waterschap Aa en Maas / iBabs
- Wetterskip Fryslân // Notubiz

first Waterschappen. Hope it will work well. Ibabs is aware and available for questions.

Best

**Comment by joepio** [comment]
Fryslan link: https://wetterskipfryslan.notubiz.nl/dashboard

**Comment by joepio** [comment]
The waterschappen seem to be imported correctly
<img width="1181" alt="Screenshot 2024-03-06 at 13 36 27" src="https://github.com/openstate/open-raadsinformatie/assets/2183313/f84b39ce-078a-40b6-8255-538ee35b5082">

However, I've yet to find a way to show the results in the front-end. Kind of surprised why it isn't working yet.

I can see the boolean queries that the FE produces contain the right index keys: `owi_*`

<img width="471" alt="Screenshot 2024-03-06 at 13 38 21" src="https://github.com/openstate/open-raadsinformatie/assets/2183313/0c592c65-dd62-47d0-853a-13fbafe0516c">

So for some reason it's being filtered out...

**Comment by breyten** [comment]
I'll look into it -- but requires reindexing stuff. Gonna try to do this so that it can run in the weekend

**Comment by joepio** [comment]
They both seem present!
