### ISSUE TITLE
Duplicate entry "Provincie Zuid-Holland"

### ISSUE THREAD

**Issue by vanderburgt** [openstate/open-raadsinformatie#449]
## Describe the bug
**Summary**
The organization select field (OrganizationSelector) contains a duplicate entry for "Provincie Zuid-Holland"

**URL / Environment**
https://openbesluitvorming.nl/

## Steps to reproduce
1. Go to https://openbesluitvorming.nl
2. Click on the organization select field and type: "Provincie"
3. See duplicate entry for "Provincie Zuid-Holland"

## Expected behavior
Only one entry for "Provincie Zuid-Holland" is shown

## Screenshots
<img width="574" alt="Screenshot 2023-11-14 at 11 01 45" src="https://github.com/openstate/open-raadsinformatie/assets/8989205/e7c5488f-659c-484e-bc7d-6c4878722e80">

## Additional context
Firefox 119.0.1 / MacOS Sonoma

**Comment by joepio** [comment]
Might be happening because they have used both GreenValley and Notubiz. I just checked their website - they now use Notubiz. I think we should remove the GreenValley source.
