### ISSUE TITLE
Too long text fields break search results

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#457]
## Describe the bug

Same as #444, unfortunately the fix to change default sort order didn't do its job completely.

From the JSON response:

```
The length of [text] field of [1651781] doc of [ori_rotterdam_20230709004025] index has exceeded [1000000] - maximum allowed to be analyzed for highlighting. This maximum can be set by changing the [index.highlight.max_analyzed_offset] index level setting. For large texts, indexing with offsets or term vectors is recommended!"                         }
```

**URL / Environment**
[link](https://openbesluitvorming.nl/?zoekterm=%22fietsenstalling%22&organisaties=%5B%22ori_rotterdam_20230709004025%22%5D&type=%5B%22MediaObject%22%5D)

## Steps to reproduce
1. Go to Openbesluitvorming.nl
2. Select "rotterdam"
3. Search for "fietsenstalling"
4. See 92 results, but none listed
5. See erorr in network

## Screenshots
<img width="1605" alt="Screenshot 2024-02-07 at 13 23 04" src="https://github.com/openstate/open-raadsinformatie/assets/2183313/a12892b3-e7d9-44fe-8883-521bbc92b1fd">

**Comment by breyten** [comment]
Fixed with 57e5de9cf18e69a2137e9a713eadf609ab0c6c7c
