### ISSUE TITLE
Amersfoort data between 2014 and 2023 missing

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#463]
Also, the amount of data seems very low (only a handful of docs in 2023?)

Might have to be re-imported + keep track of errs in log @breyten 

Perhaps related:

Rotterdam is [missing from 2015 to 2023](https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22ori_fixed_rotterdam_20230709004025%22%5D&type=%5B%22MediaObject%22%5D).

**Comment by NotuEdwin** [comment]
Bump for visibility
Is the associated bug causing this? I can read the suggestion but is this confirmed as the cause in our case?

**Comment by joepio** [comment]
Seems to be fixed for both [amersfoort](https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22ori_fixed_amersfoort_20230707120949%22%5D&type=%5B%22MediaObject%22%5D) and rotterdam!
