### ISSUE TITLE
4 Provincies missing in dropdown

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#466]
<img width="661" alt="Screenshot 2024-03-26 at 10 55 55" src="https://github.com/openstate/open-raadsinformatie/assets/2183313/ea3439a9-1444-48bf-b1d6-e5a41f790e37">

However, they are [there in the indices](https://api.openraadsinformatie.nl/v1/elastic/_cat/indices?pretty&s=i&v):
<img width="1213" alt="Screenshot 2024-03-26 at 10 56 20" src="https://github.com/openstate/open-raadsinformatie/assets/2183313/8f71f461-5acf-4242-941e-114453e1f7f6">

**Comment by joepio** [comment]
<img width="290" alt="Screenshot 2024-04-24 at 11 41 22" src="https://github.com/openstate/open-raadsinformatie/assets/2183313/96128dc6-03bd-4e1b-ad3b-f303e3c7b6b2">
They also appear in the filters (here filtering for `osi`).

I suppose the org resource is missing

**Comment by baksand** [comment]
@joepio and @breyten what is the latest status?

**Comment by ThePatricide** [comment]
There has been no update  since late April. Is there any outlook on a fix?

**Comment by joepio** [comment]
This gives the missing 4:

```sh
curl -X GET "https://api.openraadsinformatie.nl/v1/elastic/_search?q=classification:province"
```

All of these are iBabs

**Comment by joepio** [comment]
this fixed it:

```

const query = {
  size: 500,
  query: {
    bool: {
      must: {
        match_all: {},
      },
      filter: {
        bool: {
          should: [
            { match: { classification: "municipality" } },
            { match: { classification: "province" } },
            { match: { classification: "water" } },
          ],
          minimum_should_match: 1,
        },
      },
    },
  },
};
```
