### ISSUE TITLE
Remove fixed titles

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#468]
<img width="210" alt="Screenshot 2024-04-03 at 18 09 04" src="https://github.com/openstate/open-raadsinformatie/assets/2183313/2c1b3a22-65de-44ac-beac-6eebc0618d83">

**Comment by joepio** [comment]
Hmm I think this may need a front-end solution.

**Comment by breyten** [comment]
I already did a pull request in the other repo, which was merge I think. It's solved on the frontend now.

**Comment by breyten** [comment]
See https://github.com/ontola/openbesluitvorming/pull/149

**Comment by joepio** [comment]
Great, thanks! :D
