### ISSUE TITLE
Add Waterschap as Organization

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#469]
The Waterschap data is [succesfully imported](https://openbesluitvorming.nl/?zoekterm=%22wetterskip%22&type=%5B%22MediaObject%22%5D), but it's not yet possible to select them from the start screen.

I think that's because there is no _entity_ for the Waterschappen imported yet. I'm not entirely sure how this happens for Gemeenten and Provincies, but it seems likely that there is missing some logic for Waterschappen here.

The front-end does an empty query and filters for `classification: ["municipality", "province", "waterschap"]`, but there are no `waterschap` entities.

**Comment by breyten** [comment]
Ah, I updated the code to have the classification as follows:
`"classification": "Water board"`

Since the other ones are english. You should be able to find them just by searching for water, eg. [like this](https://api.openraadsinformatie.nl/v1/elastic/owi_*/_search?q=classification:water)

**Comment by joepio** [comment]
I updated the classification filter, but it's not working yet.

I can see the documents:

<img width="766" alt="Screenshot 2024-04-10 at 10 23 27" src="https://github.com/openstate/open-raadsinformatie/assets/2183313/9937db1d-de89-4681-9ad4-aa70fd9a9e6f">

But not the org:

<img width="577" alt="Screenshot 2024-04-10 at 10 23 55" src="https://github.com/openstate/open-raadsinformatie/assets/2183313/832574eb-2bb6-4e62-8068-c90c3d80164a">

**Comment by joepio** [comment]
Fixed! 

Problem was that `water board` didn't work, but `water` did in the FE query.
