### ISSUE TITLE
Sudwest Fryslan missing docs

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#478]
- Notubiz municipality, imported last month #474
- [No docs](https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22ori_sudwest_fryslan_20240704140116%22%5D&type=%5B%22MediaObject%22%5D)

@breyten:
>  kan het zijn dat Gemeente Sudwest Fryslan de api toegang niet heeft aanstaan ofzoiets? Het lijkt er op dat de requests voor de meetings wel goed gaan, maar in ORI werkt het nog niet omdat Sudwest Frylan niet in de hele lijst van gemeenten staat die je met de api op vraagt...

**Comment by joepio** [comment]
@breyten welke lijst bedoel je? Het [/organizations](https://api.notubiz.nl/organisations) endpoint denk ik? Daar zie ik idd geen Sudwest staan.

**Comment by joepio** [comment]
@NotuEdwin could it be a setting?

**Comment by NotuEdwin** [comment]
The organisation ID for them is 1512
Checks:

1. could the special chars in the name ("Gemeente Súdwest Fryslân") be an issue here?
2. are the missing documents nade available in the Gemeenteraad gremium? If they are in another gremium, ORI will never find them

**Comment by NotuEdwin** [comment]
@joepio evidently it is indeed hidden. I did some checking via postman and as you said, they are not showing up in the list if I use /organisations
I am trying to figure out what setting controls this behaviour but haven't been able to find it yet.

Retrieving information from the Notubiz API using the id once you have it seems to be working just fine, so it looks like the only issue on our end would be to retrieve the organisation id when adding a newcomer. Does this break anything on your end?

Would it be a good idea to request any newcomers to get their Notubiz organisation id from us?  That way you can add them without requiring them to be visible in the API call.

**Comment by NotuEdwin** [comment]
Update: We discovered that there is indeed a setting that hides an organisation if selected. This is used in our integration and can not be changed as it would break several of our own integrations and applications.
Please be aware that I will be leaving Notuiz per the end of this month. Please contact either Savannah or Maarten if this turns out to be a larger issue

**Comment by robvandijk** [comment]
From the information retrieved from the `/organizations` endpoint we use the `settings/folder/fields/field` information later on, to map `meeting` attributes.
If we could retrieve the information contained in the `settings/folder/fields/field` structure in a different way, we could work around the fact that some organizations are hidden from the `/organizations` endpoint. But that info does not seem to be available in other endpoints. E.g. when calling `/organizations/<orgId>` that info is not present.
So hidden organizations such as Sudwest Fryslan can presently not be retrieved.

**Comment by robvandijk** [comment]
Issue has been fixed by commit dbcd785
