### ISSUE TITLE
iBabs block as of 2024-08-06

### ISSUE THREAD

**Issue by breyten** [openstate/open-raadsinformatie#479]
## Describe the bug
**Summary**
The iBabs servers block our requests, which means we can't get any data from the for the time being. This results in lots of error, as shown by the red bars below.

**URL / Environment**
On the ORI server

## Expected behavior

In order to get the data from iBabs we need to do a lot of requests, sdince there are also quite a lot of municipalities being served by Ibabs. A more proper white listing of our server would be preferable where this cannot happpen.

## Screenshots
![image](https://github.com/user-attachments/assets/669d14fb-1467-4fa4-a726-821a246b7399)

**Comment by joepio** [comment]
I've asked iBabs for support

**Comment by joepio** [comment]
Ibabs says the block should be removed. Can you verify @breyten?

**Comment by breyten** [comment]
Yup, is working now.
