### ISSUE TITLE
Documentation on facets and filters doesn't work

### ISSUE THREAD

**Issue by konstin** [openstate/open-raadsinformatie#58]
The docs on the search ([onilne](http://docs.openraadsinformatie.nl/user/api.html#searching-within-multiple-collections), [github](https://github.com/openstate/open-raadsinformatie/blob/master/docs/user/api.rst)) say it's possible to use facets on fiilters. Those filters and facets don't seem to work anymore.

The following is the example request and its current result

```bash
$ curl -i -XPOST 'http://api.openraadsinformatie.nl/v0/search' -d '{
   "query": "vergadering",
   "facets": {
      "collection": {},
      "date": {"interval": "day"}
   },
   "size": 1
}'
```

```
HTTP/1.1 400 BAD REQUEST
Server: nginx/1.4.6 (Ubuntu)
Date: Thu, 11 Jan 2018 18:17:05 GMT
Content-Type: application/json
Content-Length: 66
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: origin, content-type, accept

{
  "error": "'date' is not a valid facet", 
  "status": "error"
}
```

Filters such as `media_content_type` don't seem to work either. (`"error": "'media_content_type' is not a valid filter"`)

**Comment by jurrian** [comment]
Since we are now using Elasticsearch 5.x, some things including facets have been deprecated. I will try to update the guide today or tomorrow to accommodate these changes.
