### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by alper** [openstate/open-raadsinformatie#62]
I spent a bit yesterday playing around with it using the [Installation guide](https://github.com/openstate/open-raadsinformatie/blob/master/INSTALL.rst) but I couldn't really get it to work very far.

Some issues:

- `docker-compose up` seems to be the most current way of getting things to run superseding steps 2&3 from the install
- But `up` doesn't seem to map my local directory into the/a virtual machine? I may be looking at this the wrong way since I'm not a huge expert but I expected to be able to edit things.
- A file called `start.sh` does not seem to exist.
- It would be nice to have a list of fixtures (with explicit commands) to import so I can get things going ASAP. I could get some of the extractors to run but it still all felt kinda sparse.

I would have made a PR for this stuff but since I'm not that well versed in the project it could be that I'm totally barking up the wrong tree. I'm interested to learn a bit more.

**Comment by jurrian** [comment]
Hi @alper, nice to hear you are trying to get it working. There have been some major changes which haven't been included in the manual yet. I will try to change it today or tomorrow.

**Comment by jurrian** [comment]
Hope this explains what you should do to get it up and running.

Feedback welcome! I'd like to know if I missed something.

**Comment by jurrian** [comment]
@breyten can you update the docs on the server?

**Comment by breyten** [comment]
Done
