### ISSUE TITLE
Supplier-ori mapping architecture

### ISSUE THREAD

**Issue by fletcher91** [openstate/open-raadsinformatie#71]
This issue describes the design for the description and mapping of properties from the data supplier to the ori project.

The system consists of two parts;
* An ontology to create resources which describe how (ETL'ed) properties map to their data supplier/extraction counterparts
* Vocabularies that express the mapping for the ori api.

The vocabularies give ori consumers the possibility to learn about the source properties in a machine-readable way, making matching 3rd party data to ori resources easier (e.g. 'what is the ori id of this scraped event?').

**Comment by jurrian** [comment]
Current progress:
Ontologies and vocubularies are now used in V1, data is modelled as such. Ontologies (i.e. [meetings](https://github.com/openstate/open-raadsinformatie/blob/master/ocd_backend/models/definitions/meeting.py)) and vocubularies (i.e. [mapping](https://github.com/openstate/open-raadsinformatie/blob/master/ocd_backend/models/definitions/mapping.py)) that are implemented as models will we published online later in owl or rdf formats.

**Comment by jurrian** [comment]
Current progress:
ORI ID's are now resolvable: http://id.openraadsinformatie.nl/43303

**Comment by jurrian** [comment]
For the last part, the vocabularies, we are going to create new nodes which will resolve. For example: `https://argu.co/voc/mapping/almelo/ibabs/identifier/6bf13765-c99f-4e64-afda-d19c97392efc` will resolve to an metadata object which is also saved in the database. See #112
