### ISSUE TITLE
Prevent the same attache documents

### ISSUE THREAD

**Issue by breyten** [openstate/open-raadsinformatie#76]
Currently happens at [Limburg](http://zoek.openstateninformatie.nl/#/g/limburg/options/N4IgZglgNgLgpgJwM4gFygMYHspThmCLAOzVHgQFsVUBtEKCSgIwFcEBzEAXQF8AaEDACeABzg1yiamnpwAbnGIwUgylkIlVIeRrgB9BUpU8BIDFACGSJBEgZLm0uiHSa9AEISorCPGKMAFZIMAAEAAoAyqaCIZYIMPoAJo5wZOAIWJRoIABMAAz5AGwAtPkAjGXlACqFqHWFAHSF+QBaIIIwWDkF5QAcZQP5udXluajlAMyok32NkwCcAKztvGZglhhwJi5xCcmp6RDKiPKWUDnCcPEga7FYCTl7iSnwHSAPSYg5X0gYt0A)

And [here](http://api.openraadsinformatie.nl/v0/limburg/events/849b38c4d87ffdaecffdb572b5493e16921e3304)

**Comment by jurrian** [comment]
Not sure if this is still the case for V1. Please reopen if the problem persists.
