### ISSUE TITLE
Regular (JSON) data dumps 

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#83]
Some users of ORI data need to have all ORI data on their local filesystem. This currently requires sending a lot of requests, which are expansive to handle. We could provide datadumps at several time intervals, e.g. daily, weekly monthly and annually.

@jurrian will work on solution, possible a Kubernetes CRON job that starts some new container that creates a JSON dump in Google Cloud.

**Comment by jurrian** [comment]
These 'data dumps' are can be saved local with `ocd_backend.utils.http.LocalCachingMixin` or in Google Cloud with `ocd_backend.utils.http.GCSCachingMixin`.

**Comment by joepio** [comment]
We got a request for this feature again (from the same user, though).

**Comment by joepio** [comment]
might help: https://github.com/taskrabbit/elasticsearch-dump

**Comment by jurrian** [comment]
The suggested elasticsearch-dump is already possible, interested parties can approach us by sending a mail to info@argu.co. In the short term I think it should not a priority to make these dumps ourselves, given that they should be cron'd, exposed, documented and all. Issue may be opened when it becomes a priority again.
