### ISSUE TITLE
Basic Elasticsearch DSL available at endpoint

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#84]
Although the current API is useful for basic REST requests, some users may require access to the full Elastic DSL. In order to do this, we need to offer the Elastic API at a seperate endpoint. We also need to adjust the CORS headers.

@jurrian is currently working on this.

**Comment by jurrian** [comment]
Based on this article I've made some changes:
https://www.elastic.co/blog/found-elasticsearch-security

**Learnings to implement:**
- [X] The endpoints will be restricted to _search, _msearch and _cat/indices
- [X] Prevent the user from overriding the index which has been specified in the URL (rest.action.multi.allow_explicit_index=false)
- [X] Disable dynamic scripting
- [X] There will be a separate elastic endpoint for admin with no restrictions using a API key
- [] Preventing Denial of Service

**Comment by breyten** [comment]
Uhm, whoops :)

**Comment by jurrian** [comment]
Elasticsearch endpoint is restricted now.

**Comment by joepio** [comment]
Related discussion about security at #145
