### ISSUE TITLE
Extract not doing much

### ISSUE THREAD

**Issue by bliekp** [openstate/open-raadsinformatie#88]
I have a fresh copy of ORI running in docker containers. All seems well so far. However, when I try an extract nothing happens:

`sudo docker exec -it ori_backend_1 ./manage.py extract start ibabs -s edamvolendam`

`[pipeline] INFO Starting pipeline for source: edamvolendam_municipality
[pipeline] DEBUG Starting run with identifier pipeline_43d78ba329a94542b1f730560c43453a
[odata] INFO Searching for: {'Title': 'Edam-Volendam'}
[odata] DEBUG {u'CategoryGroupID': None, u'Description': u'Gemeentelijke herindeling per 01-01-2016\r\nNaamswijziging per 01-01-1975', u'Key': u'GM0385   ', u'Title': u'Edam-Volendam'}
[pipeline] INFO Waiting for last chain to finish`
I let it run for over an hour but nothing is happening and I see no network traffic.
What am I doing wrong here?

**Comment by jurrian** [comment]
Which version (branch?) are you using?
By default `wait_until_finished: true` in sources/ibabs.yaml will cause the extract script to wait until everything has been processed. Setting this to false will fire all the extract commands at once and terminate when that's done.
It seems that Celery does not receive any task to process, thus the extract script will hang indefinitely.
There should be Celery processing activity in the backend logs. What does `sudo docker logs ori_backend_1` say?

**Comment by bliekp** [comment]
I changed mentioned setting to false and now this is what I get:

`$ sudo docker exec -it ori_backend_1 ./manage.py extract start ibabs -s edamvolendam
[pipeline] INFO Starting pipeline for source: edamvolendam_municipality
[pipeline] DEBUG Starting run with identifier pipeline_c2f02b830abf40a58d363f26e8bac3bd
[odata] INFO Searching for: {'Title': 'Edam-Volendam'}
[odata] DEBUG {u'CategoryGroupID': None, u'Description': u'Gemeentelijke herindeling per 01-01-2016\r\nNaamswijziging per 01-01-1975', u'Key': u'GM0385   ', u'Title': u'Edam-Volendam'}
[pipeline] INFO Starting pipeline for source: edamvolendam_committees
[pipeline] DEBUG Starting run with identifier pipeline_7b53f71eb8df4265b25ac03f731fff84
[ibabs] INFO Getting committees with designator: commissie
[ibabs] WARNING SOAP service error for edamvolendam: IPaddress 212.127.183.210 has no access to site EdamVolendam!
[pipeline] INFO Starting pipeline for source: edamvolendam_organizations
[pipeline] DEBUG Starting run with identifier pipeline_33b95f70d6f0427abd59cff37cc986b4
[pipeline] INFO Starting pipeline for source: edamvolendam_persons
[pipeline] DEBUG Starting run with identifier pipeline_c9469dbb0c2d41cda07ff2b678358f39
[pipeline] INFO Starting pipeline for source: edamvolendam_meetings
[pipeline] DEBUG Starting run with identifier pipeline_88b95ee342ab4d76932c7049cfc3b18f
[ibabs] INFO Edamvolendam: Now processing meetings from 2018-09-20 20:06:52.954602 to 2018-10-05 20:06:52.954602
[pipeline] ERROR An exception has occured in the "<class 'ocd_backend.extractors.ibabs.IBabsMeetingsExtractor'>" extractor. Setting status of run identifier "pipeline_88b95ee342ab4d76932c7049cfc3b18f" to "error":
'NoneType' object has no attribute '__getitem__'
2018-10-05 20:06:53,161 - [bugsnag] WARNING - No API key configured, couldn't notify
[client] WARNING No API key configured, couldn't notify
2018-10-05 20:06:53,161 [MainThread  ] [WARNI]  No API key configured, couldn't notify
Traceback (most recent call last):
  File "./manage.py", line 656, in <module>
    cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 752, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 761, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 752, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 761, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 653, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "./manage.py", line 386, in extract_start
    setup_pipeline(new_source)
  File "/opt/ori/ocd_backend/pipeline.py", line 118, in setup_pipeline
    source_definition=pipeline_definitions[pipeline['id']]).run():
  File "/opt/ori/ocd_backend/extractors/ibabs.py", line 99, in run
    meeting_types = self._meetingtypes_as_dict()
  File "/opt/ori/ocd_backend/extractors/ibabs.py", line 72, in _meetingtypes_as_dict
    for o in self.client.service.GetMeetingtypes(self.source_definition['sitename']).Meetingtypes[0]:
TypeError: 'NoneType' object has no attribute '__getitem__'
`

The logs:

`$ sudo docker logs ori_backend_1
celery multi v4.1.1 (latentcall)
[command] INFO Visit me at http://localhost:5555
2018-10-05 10:46:55,089 [MainThread  ] [INFO ]  Visit me at http://localhost:5555
[command] INFO Broker: redis://redis:6379/0
2018-10-05 10:46:55,104 [MainThread  ] [INFO ]  Broker: redis://redis:6379/0
[command] INFO Registered tasks:
[u'celery.accumulate',
 u'celery.backend_cleanup',
 u'celery.chain',
 u'celery.chord',
2018-10-05 10:46:55,109 [MainThread  ] [INFO ]  Registered tasks:
[u'celery.accumulate',
 u'celery.backend_cleanup',
 u'celery.chain',
 u'celery.chord',
 u'celery.chord_unlock',
 u'celery.chunks',
 u'celery.group',
 u'celery.map',
 u'celery.starmap',
 u'ocd_backend.RegisterTask',
 u'ocd_backend.enrichers.BaseEnricher',
 u'ocd_backend.enrichers.media_enricher.MediaEnricher',
 u'ocd_backend.enrichers.media_enricher.static.StaticMediaEnricher',
 u'ocd_backend.loaders.BaseLoader',
 u'ocd_backend.loaders.DummyLoader',
 u'ocd_backend.loaders.ElasticsearchLoader',
 u'ocd_backend.loaders.ElasticsearchUpdateOnlyLoader',
 u'ocd_backend.loaders.ElasticsearchUpsertLoader',
 u'ocd_backend.loaders.PopitLoader',
 u'ocd_backend.tasks.BaseCleanup',
 u'ocd_backend.tasks.CleanupElasticsearch',
 u'ocd_backend.tasks.DummyCleanup',
 u'ocd_backend.transformers.BaseTransformer',
 u'ocd_backend.transformers.ggm.GegevensmagazijnTransformer']
 u'celery.chord_unlock',
 u'celery.chunks',
 u'celery.group',
 u'celery.map',
 u'celery.starmap',
 u'ocd_backend.RegisterTask',
 u'ocd_backend.enrichers.BaseEnricher',
 u'ocd_backend.enrichers.media_enricher.MediaEnricher',
 u'ocd_backend.enrichers.media_enricher.static.StaticMediaEnricher',
 u'ocd_backend.loaders.BaseLoader',
 u'ocd_backend.loaders.DummyLoader',
 u'ocd_backend.loaders.ElasticsearchLoader',
 u'ocd_backend.loaders.ElasticsearchUpdateOnlyLoader',
 u'ocd_backend.loaders.ElasticsearchUpsertLoader',
 u'ocd_backend.loaders.PopitLoader',
 u'ocd_backend.tasks.BaseCleanup',
 u'ocd_backend.tasks.CleanupElasticsearch',
 u'ocd_backend.tasks.DummyCleanup',
 u'ocd_backend.transformers.BaseTransformer',
 u'ocd_backend.transformers.ggm.GegevensmagazijnTransformer']
> Starting nodes...
    > celery1@e341212b2bf7: OK
    > celery2@e341212b2bf7: OK
    > celery3@e341212b2bf7: OK
    > celery4@e341212b2bf7: OK
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/opt/ori/ocd_backend/ MODIFY result_backends.pyc
Fri Oct  5 10:47:01 CEST 2018
celery multi v4.1.1 (latentcall)
ERROR: Pidfile (/var/run/celery/celery2.pid) already exists.
Seems we're already running? (pid: 48)
ERROR: Pidfile (/var/run/celery/celery3.pid) already exists.
Seems we're already running? (pid: 56)
ERROR: Pidfile (/var/run/celery/celery4.pid) already exists.
Seems we're already running? (pid: 64)
> Restarting node celery2@e341212b2bf7: OK
> Restarting node celery3@e341212b2bf7: OK
> Restarting node celery4@e341212b2bf7: OK
> Stopping nodes...
    > celery1@e341212b2bf7: TERM -> 27
> Waiting for 1 node -> 27.....
    > celery1@e341212b2bf7: OK
> Restarting node celery1@e341212b2bf7: OK
> Waiting for 1 node -> None...
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/opt/ori/ocd_backend/ MODIFY pipeline.pyc
Fri Oct  5 10:49:24 CEST 2018
celery multi v4.1.1 (latentcall)
> Stopping nodes...
    > celery3@e341212b2bf7: TERM -> 56
    > celery4@e341212b2bf7: TERM -> 64
    > celery1@e341212b2bf7: TERM -> 188
    > celery2@e341212b2bf7: TERM -> 48
> Waiting for 4 nodes -> 56, 64, 188, 48........
    > celery3@e341212b2bf7: OK
> Restarting node celery3@e341212b2bf7: OK
> Waiting for 4 nodes -> None, None, None, None....
    > celery4@e341212b2bf7: OK
> Restarting node celery4@e341212b2bf7: OK
> Waiting for 3 nodes -> None, None, None....
    > celery1@e341212b2bf7: OK
> Restarting node celery1@e341212b2bf7: OK
> Waiting for 2 nodes -> None, None....
    > celery2@e341212b2bf7: OK
> Restarting node celery2@e341212b2bf7: OK
> Waiting for 1 node -> None...
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/opt/ori/ocd_backend/extractors/ MODIFY ibabs.pyc
Fri Oct  5 12:03:03 CEST 2018
celery multi v4.1.1 (latentcall)
> Stopping nodes...
    > celery3@e341212b2bf7: TERM -> 238
    > celery4@e341212b2bf7: TERM -> 246
    > celery1@e341212b2bf7: TERM -> 254
    > celery2@e341212b2bf7: TERM -> 262
> Waiting for 4 nodes -> 238, 246, 254, 262........
    > celery3@e341212b2bf7: OK
> Restarting node celery3@e341212b2bf7: OK
> Waiting for 4 nodes -> None, None, None, None....
    > celery4@e341212b2bf7: OK
> Restarting node celery4@e341212b2bf7: OK
> Waiting for 3 nodes -> None, None, None....
    > celery1@e341212b2bf7: OK
> Restarting node celery1@e341212b2bf7: OK
> Waiting for 2 nodes -> None, None....
    > celery2@e341212b2bf7: OK
> Restarting node celery2@e341212b2bf7: OK
> Waiting for 1 node -> None...
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/opt/ori/ocd_backend/sources/ MODIFY ibabs.yaml
Fri Oct  5 20:05:40 CEST 2018
celery multi v4.1.1 (latentcall)
> Stopping nodes...
    > celery3@e341212b2bf7: TERM -> 455
    > celery4@e341212b2bf7: TERM -> 463
    > celery1@e341212b2bf7: TERM -> 471
    > celery2@e341212b2bf7: TERM -> 479
> Waiting for 4 nodes -> 455, 463, 471, 479........
    > celery3@e341212b2bf7: OK
> Restarting node celery3@e341212b2bf7: OK
> Waiting for 4 nodes -> None, None, None, None....
    > celery4@e341212b2bf7: OK
> Restarting node celery4@e341212b2bf7: OK
> Waiting for 3 nodes -> None, None, None....
    > celery1@e341212b2bf7: OK
> Restarting node celery1@e341212b2bf7: OK
> Waiting for 2 nodes -> None, None....
    > celery2@e341212b2bf7: OK
> Restarting node celery2@e341212b2bf7: OK
> Waiting for 1 node -> None...
celery multi v4.1.1 (latentcall)
[command] INFO Visit me at http://localhost:5555
2018-10-05 20:06:40,682 [MainThread  ] [INFO ]  Visit me at http://localhost:5555
[command] INFO Broker: redis://redis:6379/0
2018-10-05 20:06:40,704 [MainThread  ] [INFO ]  Broker: redis://redis:6379/0
[command] INFO Registered tasks:
[u'celery.accumulate',
 u'celery.backend_cleanup',
 u'celery.chain',
 u'celery.chord',
 u'celery.chord_unlock',
 u'celery.chunks',
 u'celery.group',
 u'celery.map',
 u'celery.starmap',
 u'ocd_backend.RegisterTask',
 u'ocd_backend.enrichers.BaseEnricher',
 u'ocd_backend.enrichers.media_enricher.MediaEnricher',
 u'ocd_backend.enrichers.media_enricher.static.StaticMediaEnricher',
 u'ocd_backend.loaders.BaseLoader',
 u'ocd_backend.loaders.DummyLoader',
 u'ocd_backend.loaders.ElasticsearchLoader',
 u'ocd_backend.loaders.ElasticsearchUpdateOnlyLoader',
 u'ocd_backend.loaders.ElasticsearchUpsertLoader',
 u'ocd_backend.loaders.PopitLoader',
 u'ocd_backend.tasks.BaseCleanup',
 u'ocd_backend.tasks.CleanupElasticsearch',
 u'ocd_backend.tasks.DummyCleanup',
 u'ocd_backend.transformers.BaseTransformer',
 u'ocd_backend.transformers.ggm.GegevensmagazijnTransformer']
2018-10-05 20:06:40,708 [MainThread  ] [INFO ]  Registered tasks:
[u'celery.accumulate',
 u'celery.backend_cleanup',
 u'celery.chain',
 u'celery.chord',
 u'celery.chord_unlock',
 u'celery.chunks',
 u'celery.group',
 u'celery.map',
 u'celery.starmap',
 u'ocd_backend.RegisterTask',
 u'ocd_backend.enrichers.BaseEnricher',
 u'ocd_backend.enrichers.media_enricher.MediaEnricher',
 u'ocd_backend.enrichers.media_enricher.static.StaticMediaEnricher',
 u'ocd_backend.loaders.BaseLoader',
 u'ocd_backend.loaders.DummyLoader',
 u'ocd_backend.loaders.ElasticsearchLoader',
 u'ocd_backend.loaders.ElasticsearchUpdateOnlyLoader',
 u'ocd_backend.loaders.ElasticsearchUpsertLoader',
 u'ocd_backend.loaders.PopitLoader',
 u'ocd_backend.tasks.BaseCleanup',
 u'ocd_backend.tasks.CleanupElasticsearch',
 u'ocd_backend.tasks.DummyCleanup',
 u'ocd_backend.transformers.BaseTransformer',
 u'ocd_backend.transformers.ggm.GegevensmagazijnTransformer']
Stale pidfile exists - Removing it.
> Starting nodes...
    > celery1@e341212b2bf7: OK
    > celery2@e341212b2bf7: OK
    > celery3@e341212b2bf7: OK
    > celery4@e341212b2bf7: OK
Stale pidfile exists - Removing it.
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/opt/ori/ocd_backend/extractors/ MODIFY almanak.pyc
Fri Oct  5 20:06:52 CEST 2018
celery multi v4.1.1 (latentcall)
> Stopping nodes...
    > celery3@e341212b2bf7: TERM -> 56
    > celery4@e341212b2bf7: TERM -> 64
    > celery1@e341212b2bf7: TERM -> 27
    > celery2@e341212b2bf7: TERM -> 48
> Waiting for 4 nodes -> 56, 64, 27, 48........
    > celery3@e341212b2bf7: OK
> Restarting node celery3@e341212b2bf7: OK
> Waiting for 4 nodes -> None, None, None, None....
    > celery4@e341212b2bf7: OK
> Restarting node celery4@e341212b2bf7: OK
> Waiting for 3 nodes -> None, None, None....
    > celery1@e341212b2bf7: OK
> Restarting node celery1@e341212b2bf7: OK
> Waiting for 2 nodes -> None, None....
    > celery2@e341212b2bf7: OK
> Restarting node celery2@e341212b2bf7: OK
> Waiting for 1 node -> None...
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.`

I'm running the master branch...

**Comment by jurrian** [comment]
iBabs requires you to be on their whitelist before being able to extract their entities. I guess that would be the last step here to complete the task. Have you tried the suppliers Notubiz or GemeenteOplossingen? If I remember correctly they do not require a form of authentication.

**Comment by bliekp** [comment]
Apparently not....

`pim@xiaomi-ubuntu:~/Development/open-raadsinformatie$ sudo docker exec -it ori_backend_1 ./manage.py extract start notubiz -s epe -e meetings
[pipeline] INFO Starting pipeline for source: epe_meetings
[pipeline] DEBUG Starting run with identifier pipeline_a17c211e1e084b468d0b0560168a1e09
[pipeline] ERROR An exception has occured in the "<class 'ocd_backend.extractors.notubiz.NotubizMeetingExtractor'>" extractor. Setting status of run identifier "pipeline_a17c211e1e084b468d0b0560168a1e09" to "error":
HTTPSConnectionPool(host='api.notubiz.nl', port=443): Max retries exceeded with url: /organisations?format=json&version=1.10.8 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f785fbbcc50>: Failed to establish a new connection: [Errno -3] Try again',))
2018-10-12 10:32:49,400 - [bugsnag] WARNING - No API key configured, couldn't notify
[client] WARNING No API key configured, couldn't notify
2018-10-12 10:32:49,400 [MainThread  ] [WARNI]  No API key configured, couldn't notify
Traceback (most recent call last):
  File "./manage.py", line 656, in <module>
    cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 752, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 761, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 752, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 761, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 653, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "./manage.py", line 386, in extract_start
    setup_pipeline(new_source)
  File "/opt/ori/ocd_backend/pipeline.py", line 118, in setup_pipeline
    source_definition=pipeline_definitions[pipeline['id']]).run():
  File "/opt/ori/ocd_backend/extractors/notubiz.py", line 27, in run
    "?format=json&version=1.10.8" % self.base_url
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.notubiz.nl', port=443): Max retries exceeded with url: /organisations?format=json&version=1.10.8 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f785fbbcc50>: Failed to establish a new connection: [Errno -3] Try again',))
pim@xiaomi-ubuntu:~/Development/open-raadsinformatie$ sudo docker exec -it ori_backend_1 ./manage.py extract start go -s beemster -e meetings
[pipeline] INFO Starting pipeline for source: beemster_meetings
[pipeline] DEBUG Starting run with identifier pipeline_dd1e6ef7afac46aaa58178b90bbcdccc
[pipeline] ERROR An exception has occured in the "<class 'ocd_backend.extractors.goapi.GemeenteOplossingenMeetingsExtractor'>" extractor. Setting status of run identifier "pipeline_dd1e6ef7afac46aaa58178b90bbcdccc" to "error":
HTTPSConnectionPool(host='gemeentebestuur.beemster.net', port=443): Max retries exceeded with url: /api/v1/meetings?date_from=1538044444&date_to=1539340444 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7c88763b90>: Failed to establish a new connection: [Errno -3] Try again',))
2018-10-12 10:34:09,485 - [bugsnag] WARNING - No API key configured, couldn't notify
[client] WARNING No API key configured, couldn't notify
2018-10-12 10:34:09,485 [MainThread  ] [WARNI]  No API key configured, couldn't notify
Traceback (most recent call last):
  File "./manage.py", line 656, in <module>
    cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 752, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 761, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 752, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 761, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 653, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "./manage.py", line 386, in extract_start
    setup_pipeline(new_source)
  File "/opt/ori/ocd_backend/pipeline.py", line 118, in setup_pipeline
    source_definition=pipeline_definitions[pipeline['id']]).run():
  File "/opt/ori/ocd_backend/extractors/goapi.py", line 55, in run
    (end_date - datetime(1970, 1, 1)).total_seconds()
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gemeentebestuur.beemster.net', port=443): Max retries exceeded with url: /api/v1/meetings?date_from=1538044444&date_to=1539340444 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7c88763b90>: Failed to establish a new connection: [Errno -3] Try again',))
`

**Comment by jurrian** [comment]
Strange, the [URL in the last lines](https://gemeentebestuur.beemster.net/api/v1/meetings?date_from=1538044444&date_to=1539340444) of the error message does return correct results on my pc, I have also tried using a proxy to see if some kind of whitelist is active

It might have been a temporary problem, can you please retry again? `ConnectionError ... Max retries exceeded with url` suggests it has to do with your network connection to the server.

**Comment by jurrian** [comment]
Closing this for now, let me know if the problem persists.
