### ISSUE TITLE
Sources index is limited, no size query parameter is possible

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#90]
I'd like to see all the available sources, but both in v0 and v1, the output is limited to 10 items. Adding a query parameter (e.g. `sources?size=1000`) does not seem to be working.

**Comment by breyten** [comment]
Only closed for v0

**Comment by voodoo-burger** [comment]
Is this pertaining to ElasticSearch? If so this is already possible: http://beta.openraadsinformatie.nl/v1/elastic/ori_leusden*/_search?size=50 .
