### ISSUE TITLE
'Committee' type organizations should have a name and a classification

### ISSUE THREAD

**Issue by breyten** [openstate/open-raadsinformatie#95]
They currently do not have these fields:

```curl -XPOST 'http://beta.openraadsinformatie.nl/v1/elastic/ori_*/organization/_search' -d '{"aggs":{"name":{"terms": {"field": "name.keyword", "size": 100}}}, "size": 0}' |jq '.'```

Currently lists a list of 48 municipalities. 

```curl -XPOST 'http://beta.openraadsinformatie.nl/v1/elastic/ori_*/organization/_search' -d '{"aggs":{"name":{"terms": {"field": "classification.keyword", "size": 100}}}, "size": 0}' |jq '.'```

Returns the following:
```
{
  "took": 152,
  "timed_out": false,
  "_shards": {
    "total": 290,
    "successful": 290,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 165,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "name": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "Municipality",
          "doc_count": 48
        }
      ]
    }
  }
}
```

**Comment by voodoo-burger** [comment]
The current implementation of `classification` varies a lot by source and item. It seems to me that classification should follow the item type (but with a little more freedom), like municipality, council, committee, person, party, document, etc. instead of being set dynamically from the source like this example:

`event.classification = [self.original_item['documentTypeLabel']]`

Is this correct?

**Comment by breyten** [comment]
The problem is that all of the 355 municipalities do not have the same classifications. So you'll end up with hundreds or possibly thousands of entities (Ie. some call their meeting notes 'notulen', while others call them 'verslag').

**Comment by voodoo-burger** [comment]
> The problem is that all of the 355 municipalities do not have the same classifications. So you'll end up with hundreds or possibly thousands of entities (Ie. some call their meeting notes 'notulen', while others call them 'verslag').

That is why I would suggest to not take the classification from the source but keep it to a few pre-defined values like `document`. That way it is consistent across sources.

**Comment by breyten** [comment]
You will still have to translate the many to few, which is exactly the problem (Ie. this requires a mapping for every munucipality)

**Comment by voodoo-burger** [comment]
For this issue I have solved it by giving committees a `Council`, `Committee` or `Subcommittee` (iBabs only) subcommittee. It's not 100% fool-proof though.
