### ISSUE TITLE
Splitting document texts into smaller units

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#96]
Currently, all imported (PDF) documents are scraped and turned into a single string. This enables full-text search in Elastic.

However, this limits the usability of full-text search, since we can't know where in a document the text is actually hit. This means that if a user search for a term, we can't open the relevant page when the user clicks on the result.

This could be fixed in a number of ways:

1. Split the plain text into an array of strings, each string represents a single page.
2. Create new resources for every page, each with their own ID and URL. 
3. Convert the text into XML, which has support for pagination.  

Wondering what your thoughts are on this! @jurrian @breyten

**Comment by jurrian** [comment]
Option 1 sounds good to me.
