### ISSUE TITLE
Rename ori_resolver and ori_usage_logs

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#98]
When using the [ori_* endpoint of V1 ](https://api.openraadsinformatie.nl/v1/elastic/ori_*/_search), some irrelevant aggregates appear, such as the types `search`, `url`, `sources` and `get_object`. This causes them to appear in the search filter component for `_type`.

Renaming the `ori_resolver` and `ori_usage_logs` indexes to something that does not start with `ori_*` should fix this.

**Comment by voodoo-burger** [comment]
Seems like a simple enough fix... Change the USAGE_LOGGING_INDEX and RESOLVER_URL_INDEX settings.

**Comment by jurrian** [comment]
Agreed. Since resolver and usage_logs are system global they should not have the prefix so `ori_resolver` should become `resolver`
