### ISSUE TITLE
Remove agenda bundles

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#99]
Many municipality registrars bundle all attachments in a single PDF, which is included in every meeting. This makes their life a little easier, since they can print all the required files at once. For this project, however, it causes some problems:

- Duplicate data negatively impacts the search UX, since users are shown the same result twice. - It impacts TF/IDF or other significant term detection algorithms, since it will make some really rare words occur twice, in seperate clusters.
- It doubles the amount of storage that we need, which makes the cost higher
- It causes some users to share low-quality URLS to bundles, instead of the original documents.

So how should we deal with this? Some ideas:

1. Set a cut-off point for page length. Easy to implement, but it will miss some bundles and it will discard some useful non-bundle documents.
2. Check for "Agendabundel" and similar words in the title of a document. It will require some manual checks to match most, and it will cause some false positives.
3. For each meeting, after checking the content of all the documents, try a couple of sentences of plaintext from the non-largest document and see if these sentences appear in the largest document of the meeting. If that is the case, the largest document is the bundle and it can be discarded.

**Comment by breyten** [comment]
For v0 we kind of deal with this by not scanning the entire document. On the top of my head we do the first 20 pages (The `pdf_max_pages` setting), which deals with the double problem a bit.

**Comment by jurrian** [comment]
This cutoff point at 20 pages is still the case at v1 but it doesn't prevent at least the first 20 pages from being double.
